# Generated by Django 2.0 on 2019-09-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='color',
            field=models.CharField(default='#e94e1b', help_text="Qualsevol color CSS vàlid, incloent-hi 'red', 'green', etc.", max_length=7, verbose_name='color al calendari'),
        ),
    ]
