# Generated by Django 2.0 on 2019-09-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0002_auto_20190923_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_reservations.Room', verbose_name='sala'),
        ),
    ]
