# Generated by Django 2.0 on 2019-09-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0003_auto_20190923_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='url',
            field=models.CharField(blank=True, help_text="En cas d'indicar-se, l'esdeveniment del calendari podrà clicar-se i portarà cap a aquest enllaç.", max_length=250, null=True, verbose_name='enllaç web'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facilities_reservations.Room', verbose_name='sala'),
        ),
    ]
