# Generated by Django 3.2.14 on 2022-07-21 14:28

import apps.coopolis.storage_backends
from django.db import migrations, models
import easy_thumbnails.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='títol')),
                ('objectives', models.TextField(null=True, verbose_name='descripció')),
                ('date_start', models.DateField(verbose_name='dia inici')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='dia finalització')),
                ('starting_time', models.TimeField(verbose_name="hora d'inici")),
                ('ending_time', models.TimeField(verbose_name='hora de finalització')),
                ('spots', models.IntegerField(default=0, help_text="Si hi ha inscripcions en llista d'espera i augmentes el número de places, passaran a confirmades i se'ls hi notificarà el canvi. Si redueixes el número de places per sota del total d'inscrites les que ja estaven confirmades seguiran confirmades. Aquestes autotatitzacions únicament s'activen si la sessió té una data futura.", verbose_name='places totals')),
                ('service', models.SmallIntegerField(blank=True, choices=[(None, 'Cap'), (10, 'Servei de mapatge i diagnosi'), (20, 'Servei de Divulgació, Sensibilització i Generació de Coneixement.'), (30, "Servei de Formació per a la promoció, creació i consolidació de cooperatives i projectes de l'ESS."), (40, "Servei d'Acompanyament per la creació i consolidació de cooperatives i projectes de l'ESS."), (50, 'Servei de Facilitació de la Intercooperació, treball en xarxa i dinamització territorial.'), (60, "Punt d'informació sobre l'ESS.")], null=True, verbose_name='Servei')),
                ('photo1', models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='fotografia')),
                ('photo3', models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='fotografia 2')),
                ('photo2', models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='document acreditatiu')),
                ('file1', models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='material de difusió')),
                ('publish', models.BooleanField(default=True, verbose_name='publicada')),
                ('for_minors', models.BooleanField(default=False, help_text="Determina el tipus de justificació i en aquest cas, s'han d'omplir els camps relatius a menors.", verbose_name='acció dirigida a menors')),
                ('minors_school_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='nom del centre educatiu')),
                ('minors_school_cif', models.CharField(blank=True, max_length=12, null=True, verbose_name='CIF del centre educatiu')),
                ('minors_grade', models.CharField(blank=True, choices=[('PRIM', 'Primària'), ('ESO', 'Secundària obligatòria'), ('BATX', 'Batxillerat'), ('FPGM', 'Formació professional grau mig'), ('FPGS', 'Formació professional grau superior')], max_length=4, null=True, verbose_name="grau d'estudis")),
                ('minors_participants_number', models.IntegerField(blank=True, null=True, verbose_name="número d'alumnes participants")),
                ('videocall_url', models.URLField(blank=True, max_length=250, null=True, verbose_name='enllaç a la videotrucada')),
                ('instructions', models.TextField(blank=True, help_text='Aquest text s\'inclourà al correu de recordatori. És molt important que el formateig del text sigui el menor possible, i en particular, que si copieu i enganxeu el text d\'algun altre lloc cap aquí, ho feu amb l\'opció "enganxar sense format", ja que sinó arrossegarà molta informació de formateig que probablement farà que el correu es vegi malament.', null=True, verbose_name='instruccions per participar')),
                ('poll_sent', models.DateTimeField(blank=True, null=True, verbose_name="data d'enviament de l'enquesta")),
            ],
            options={
                'verbose_name': 'sessió',
                'verbose_name_plural': 'sessions',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True, null=True, verbose_name="data d'inscripció")),
                ('user_comments', models.TextField(blank=True, null=True, verbose_name='comentaris')),
                ('waiting_list', models.BooleanField(default=False, verbose_name="en llista d'espera")),
                ('reminder_sent', models.DateTimeField(blank=True, null=True, verbose_name='Recordatori enviat')),
            ],
            options={
                'verbose_name': 'inscripció',
                'verbose_name_plural': 'inscripcions',
                'db_table': 'cc_courses_activity_enrolled',
            },
        ),
        migrations.CreateModel(
            name='ActivityResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='fitxer')),
                ('name', models.CharField(max_length=120, verbose_name='nom del recurs')),
            ],
            options={
                'verbose_name': 'recurs',
                'verbose_name_plural': 'recursos i material formatiu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='títol')),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('date_start', models.DateField(verbose_name='dia inici')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='dia finalització')),
                ('hours', models.CharField(help_text='Indica només els horaris, sense els dies.', max_length=200, verbose_name='horaris')),
                ('description', models.TextField(null=True, verbose_name='descripció')),
                ('publish', models.BooleanField(verbose_name='publicat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de creació')),
                ('banner', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
            options={
                'verbose_name': 'acció',
                'verbose_name_plural': 'accions',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='CoursePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('address', models.CharField(max_length=200, verbose_name='adreça')),
            ],
            options={
                'verbose_name': 'lloc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('legal_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='N.I.F.')),
                ('is_active', models.BooleanField(default=True, help_text='Si la desactives no apareixerà al desplegable.', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'entitat',
                'verbose_name_plural': 'entitats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'organitzadora',
                'verbose_name_plural': 'organitzadores',
                'ordering': ['name'],
            },
        ),
    ]
