# Generated by Django 3.2.14 on 2022-11-21 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cc_courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityenrolled',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='persona'),
        ),
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(help_text="Escriu el nom de l'acció i selecciona-la del desplegable. Si no existeix, clica a la lupa i després a 'Crear acció'.", on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cc_courses.course', verbose_name='acció'),
        ),
        migrations.AddField(
            model_name='activity',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled_activities', through='cc_courses.ActivityEnrolled', to=settings.AUTH_USER_MODEL, verbose_name='inscrites'),
        ),
        migrations.AddField(
            model_name='activity',
            name='entities',
            field=models.ManyToManyField(blank=True, help_text="Escriu el nom de l'entitat i selecciona-la del desplegable. Si no existeix, clica a la lupa i després a 'Crear entitat'.", related_name='entities', to='cc_courses.Entity', verbose_name='entitats organitzadores'),
        ),
        migrations.AddField(
            model_name='activity',
            name='minors_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='docent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.organizer', verbose_name='organitzadora'),
        ),
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.courseplace', verbose_name='lloc'),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text="Persona de l'equip al càrrec de la sessió. Per aparèixer al desplegable, cal que la persona tingui activada l'opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_responsible', to=settings.AUTH_USER_MODEL, verbose_name='persona responsable'),
        ),
        migrations.AddField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Si selecciones una sala, quan guardis quedarà reservada per la sessió. <br>Consulta el <a href="/reservations/calendar/" target="_blank">CALENDARI DE RESERVES</a> per veure la disponibilitat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='facilities_reservations.room', verbose_name='sala'),
        ),
        migrations.AddField(
            model_name='activity',
            name='room_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activities', to='facilities_reservations.reservation'),
        ),
        migrations.AlterUniqueTogether(
            name='activityenrolled',
            unique_together={('user', 'activity')},
        ),
    ]
