# Generated by Django 3.2.14 on 2022-11-22 14:51

import apps.coopolis.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='fitxer adjunt')),
                ('file_type', models.CharField(choices=[('WORK', 'De treball'), ('JUSTIFICATION', 'Justificatori')], max_length=50, verbose_name='tipus de fitxer')),
                ('url', models.URLField(blank=True, null=True, verbose_name='fitxer enllaçat')),
                ('name', models.CharField(help_text="Pensa un nom prou descriptiu com perquè ajudi a altres persones a preparar possibles requeriments d'aquí uns mesos o anys.", max_length=120, verbose_name='nom del fitxer')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cc_courses.activity')),
            ],
            options={
                'verbose_name': 'fitxer',
                'verbose_name_plural': 'fitxers i enllaços interns',
                'ordering': ['name'],
            },
        ),
    ]
