# Generated by Django 3.2.14 on 2022-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='entities', to='cc_courses.Entity', verbose_name='entitats organitzadores'),
        ),
    ]
