# Generated by Django 3.2.14 on 2022-11-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0003_activity_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='entity',
        ),
    ]
