# Generated by Django 2.1.3 on 2019-04-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0003_auto_20190311_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cc_courses.Course', verbose_name='formació / programa'),
        ),
    ]
