# Generated by Django 2.1.3 on 2019-04-10 16:08

import apps.cc_courses.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0004_auto_20190410_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=250, null=True),
        ),
    ]
