# Generated by Django 3.2.14 on 2024-04-29 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities_reservations', '0001_initial'),
        ('cc_courses', '0004_auto_20221122_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date_start'], 'verbose_name': 'activitat', 'verbose_name_plural': 'activitats'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text="Persona de l'equip al càrrec de l'activitat. Per aparèixer al desplegable, cal que la persona tingui activada l'opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_responsible', to=settings.AUTH_USER_MODEL, verbose_name='persona responsable'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Si selecciones una sala, quan guardis quedarà reservada per l\'activitat. <br>Consulta el <a href="/reservations/calendar/" target="_blank">CALENDARI DE RESERVES</a> per veure la disponibilitat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='facilities_reservations.room', verbose_name='sala'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='spots',
            field=models.IntegerField(default=0, help_text="Si hi ha inscripcions en llista d'espera i augmentes el número de places, passaran a confirmades i se'ls hi notificarà el canvi. Si redueixes el número de places per sota del total d'inscrites les que ja estaven confirmades seguiran confirmades. Aquestes automatitzacions únicament s'activen si l'activitat té una data futura.", verbose_name='places totals'),
        ),
        migrations.AlterField(
            model_name='activityenrolled',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cc_courses.activity', verbose_name='activitat'),
        ),
    ]
