# Generated by Django 3.2.14 on 2022-11-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0006_load_town_fixtures'),
        ('cc_courses', '0004_remove_activity_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Barri'),
        ),
        migrations.AddField(
            model_name='entity',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.town', verbose_name='municipi'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(help_text="Escriu el nom de l'acció i selecciona-la del desplegable. Si no existeix, clica a la lupa i després a 'Crear acció'.", on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cc_courses.course', verbose_name='acció'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='entities',
            field=models.ManyToManyField(blank=True, help_text="Escriu el nom de l'entitat i selecciona-la del desplegable. Si no existeix, clica a la lupa i després a 'Crear entitat'.", related_name='entities', to='cc_courses.Entity', verbose_name='entitats organitzadores'),
        ),
    ]
