# Generated by Django 2.1.3 on 2019-04-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0005_auto_20190410_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.CoursePlace', verbose_name='lloc'),
        ),
    ]
