# Generated by Django 3.2.14 on 2024-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0006_auto_20240502_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='agents_involved',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='agents implicats'),
        ),
        migrations.AddField(
            model_name='activity',
            name='communality_role',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Participant / Assistent (rol passiu)'), (2, 'Organitzador / Col·laborador (rol actiu)')], null=True, verbose_name='rol comunalitat'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descripció actuació'),
        ),
        migrations.AddField(
            model_name='activity',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estimació hores dedicació'),
        ),
        migrations.AddField(
            model_name='activity',
            name='included_project',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="projecte al qual s'engloba"),
        ),
        migrations.AddField(
            model_name='activity',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="barri on s'ha fet"),
        ),
        migrations.AddField(
            model_name='activity',
            name='networking',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Conjunta')], null=True, verbose_name='treball en xarxa'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project_sector',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'Agricultura i ramaderia'), (20, 'Alimentació i consum'), (30, 'Atenció a les persones i cures (criança, col·lectius vulnerables...)'), (40, 'Comerç (just, proximitat, etc.)'), (50, 'Cultura i oci (lleure, esport, esdeveniments...)'), (60, 'Economia circular (reciclatge, recuperació i reutilització de residus)'), (70, 'Educació / Formació'), (80, 'Feminismes LGTBIQ+'), (90, 'Finançament i assegurances (micromecenatge, finances ètiques, ....)'), (100, "Gestió i conservació de l'espai natural (gestió de residus,"), (110, 'Hosteleria i restauració'), (120, 'Industria'), (130, 'Joventut'), (140, 'Logística i mobilitat (transports, bancs de recursos, emmagatzematge...)'), (150, 'Màrqueting i comunicació (xarxes, audiovisual, arts gràfiques, disseny...)'), (160, 'Ruralitats (despoblament, relleu,...)'), (170, 'Salut (mental, sexualitat, ...)'), (180, "Serveis d'assessoria i gestoria"), (190, 'Tecnologies i innovació'), (200, 'Transició energètica / recursos naturals'), (210, 'Turisme (rural, sostenible,...)'), (220, 'Urbanisme i habitatge (arquitectura, rehabilitació, masoveria, ...)')], null=True, verbose_name='sector del projecte'),
        ),
        migrations.AddField(
            model_name='activity',
            name='types',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Acompanyament'), (2, 'Acte'), (3, 'Cartografia /mapeig'), (4, 'Cicle'), (5, 'Entrevista'), (6, 'Exposició'), (7, 'Festival'), (8, 'Fira'), (9, 'Inauguració'), (10, 'Jornada'), (11, 'Premi'), (12, 'Presentació'), (13, 'Publicació'), (14, 'Punt informació'), (15, 'Reunió'), (16, 'Sessió formativa/ informativa'), (17, 'Taller'), (18, 'Trobada'), (19, 'Trobades assemblea'), (20, 'Visita'), (21, 'Xerrada')], null=True, verbose_name='tipus actuació'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='service',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Cap'), (10, "A) Serveis d'anàlisis i prospectiva"), (20, "B) Servei de formació i difusió per a l'activisme"), (30, "C) Servei de formació per a la creació i l'establiment de projectes d'ajuda mútua"), (40, "D) Servei per a la creació i consolidació de projectes d'ajuda mútua, d'intercooperació i de cooperació entre els bens comuns urbans i la ciutadania"), (50, "E) Punt de trobada i d'informació de comunalitat urbana"), (60, "A) Serveis d'anàlisis i prospectiva"), (70, "B) Servei de formació i difusió per a l'activisme al barri/espai urbà adreçat a entitats i persones"), (80, "C) Servei de foment a projectes d'ajuda mútua, d'intercooperació i de cooperació entre els bens comuns urbans i la ciutadania"), (90, "D) Servei d’acompanyament a la creació i a la consolidació de projectes d'ajuda mútua")], help_text='Els Serveis disponibles s\'actualitzen segons la convocatòria, que es calcula amb el valor del camp "Data d\'inici".', null=True, verbose_name='Servei'),
        ),
    ]
