# Generated by Django 3.2.14 on 2024-07-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0008_auto_20240718_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(help_text="Escriu el nom del projecte i selecciona'l del desplegable. Si no existeix, clica a la lupa i després a 'Crear projecte'.", on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cc_courses.course', verbose_name="Projecte al qual s'engloba"),
        ),
    ]
