# Generated by Django 2.1.3 on 2019-04-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0008_auto_20190410_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date_start'], 'verbose_name': 'sessió', 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-date_start'], 'verbose_name': 'acció', 'verbose_name_plural': 'accions'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cc_courses.Course', verbose_name='acció'),
        ),
    ]
