# Generated by Django 2.1.3 on 2019-04-15 18:22

import apps.cc_courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0009_auto_20190415_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='scanned_signatures',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='document amb signatures'),
        ),
    ]
