# Generated by Django 2.1.3 on 2019-04-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0012_activity_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity', verbose_name='entitat'),
        ),
    ]
