# Generated by Django 2.1.3 on 2019-04-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0014_course_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date_start'], 'verbose_name': 'sessió', 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['date_start'], 'verbose_name': 'acció', 'verbose_name_plural': 'accions'},
        ),
    ]
