# Generated by Django 2.1.3 on 2019-05-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0015_auto_20190428_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'organitzadora',
                'verbose_name_plural': 'organitzadores',
            },
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'ateneu / entitat', 'verbose_name_plural': 'ateneus o entitats'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity', verbose_name='ateneu / entitat'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='legal_id',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='N.I.F.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Organizer', verbose_name='organitzadora'),
        ),
    ]
