# Generated by Django 2.1.3 on 2019-06-04 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cc_courses', '0019_auto_20190603_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='for_minors',
        ),
        migrations.AddField(
            model_name='activity',
            name='for_minors',
            field=models.BooleanField(default=False, help_text="Determina el tipus de justificació i en aquest cas, s'han d'omplir els camps relatius a menors.", verbose_name='acció dirigida a menors'),
        ),
        migrations.AddField(
            model_name='activity',
            name='minors_grade',
            field=models.CharField(blank=True, choices=[('PRIM', 'Primària'), ('ESO', 'Secundària obligatòria'), ('BATX', 'Batxillerat'), ('FPGM', 'Formació professional grau mig'), ('FPGS', 'Formació professional grau superior')], max_length=4, null=True, verbose_name="grau d'estudis"),
        ),
        migrations.AddField(
            model_name='activity',
            name='minors_participants_number',
            field=models.IntegerField(blank=True, null=True, verbose_name="número d'alumnes participants"),
        ),
        migrations.AddField(
            model_name='activity',
            name='minors_school_cif',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CIF del centre educatiu'),
        ),
        migrations.AddField(
            model_name='activity',
            name='minors_school_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nom del centre educatiu'),
        ),
        migrations.AddField(
            model_name='activity',
            name='minors_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='docent'),
        ),
    ]
