# Generated by Django 2.0.13 on 2019-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0021_courseplace_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='subaxis',
            field=models.CharField(blank=True, help_text="Correspon a 'Tipus d'acció' a la justificació.", max_length=2, null=True, verbose_name='sub-eix'),
        ),
    ]
