# Generated by Django 2.0 on 2019-09-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0024_activity_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Si selecciones una sala, quan guardis quedarà reservada per la sessió. <br>Consulta el <a href="/reservations/calendar/" target="_blank">CALENDARI DE RESERVES</a> per veure la disponibilitat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='facilities_reservations.Room', verbose_name='sala'),
        ),
    ]
