# Generated by Django 2.0 on 2019-11-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0025_auto_20190924_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='room_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activities', to='facilities_reservations.Reservation'),
        ),
    ]
