# Generated by Django 2.2.7 on 2019-11-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0027_auto_20191118_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de creació'),
        ),
    ]
