# Generated by Django 2.2.7 on 2020-01-20 10:56

import apps.cc_courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0029_auto_20200116_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='file1',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='material de difusió'),
        ),
        migrations.AddField(
            model_name='activity',
            name='photo3',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='fotografia 2'),
        ),
    ]
