# Generated by Django 2.2.7 on 2020-04-07 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cc_courses', '0031_auto_20200120_1943'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='ActivityEnrolled',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ],
                options={
                    'db_table': 'cc_courses_activity_enrolled',
                },
            ),
            migrations.AlterField(
                model_name='activity',
                name='enrolled',
                field=models.ManyToManyField(blank=True, related_name='enrolled_activities', through='cc_courses.ActivityEnrolled', to=settings.AUTH_USER_MODEL, verbose_name='inscrites'),
            ),
            migrations.AddField(
                model_name='activityenrolled',
                name='activity',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc_courses.Activity', verbose_name='sessió'),
            ),
            migrations.AddField(
                model_name='activityenrolled',
                name='user',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='persona'),
            ),
            migrations.AlterUniqueTogether(
                name='activityenrolled',
                unique_together={('user', 'activity')},
            ),
        ])
    ]
