# Generated by Django 2.2.7 on 2020-05-06 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0034_auto_20200505_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityenrolled',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cc_courses.Activity', verbose_name='sessió'),
        ),
        migrations.AlterField(
            model_name='activityenrolled',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='persona'),
        ),
    ]
