# Generated by Django 2.2.7 on 2020-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0040_auto_20200710_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityresourcefile',
            options={'ordering': ['name'], 'verbose_name': 'recurs', 'verbose_name_plural': 'recursos i material formatiu'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='instructions',
            field=models.TextField(blank=True, help_text="En un futur, aquest text s'inclourà als recordatoris que envieu a tota la gent inscrita. Ara per ara, però, l'heu d'enviar manualment.", null=True, verbose_name='instruccions per participar'),
        ),
    ]
