# Generated by Django 2.2.7 on 2021-09-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0050_auto_20210505_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='poll_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name="data d'enviament de l'enquesta"),
        ),
    ]
