# Generated by Django 3.2.9 on 2021-12-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0052_auto_20211108_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='service',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Cap'), (10, 'Servei de mapatge i diagnosi'), (20, 'Servei de Divulgació, Sensibilització i Generació de Coneixement.'), (30, "Servei de Formació per a la promoció, creació i consolidació de cooperatives i projectes de l'ESS."), (40, "Servei d'Acompanyament per la creació i consolidació de cooperatives i projectes de l'ESS."), (50, 'Servei de Facilitació de la Intercooperació, treball en xarxa i dinamització territorial.'), (60, "Punt d'informació sobre l'ESS.")], null=True, verbose_name='Servei'),
        ),
    ]
