# Generated by Django 3.2.9 on 2022-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0054_auto_20211222_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='circle',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Cap'), (0, 'Ateneu'), (1, 'Cercle 1'), (2, 'Cercle 2'), (3, 'Cercle 3'), (4, 'Cercle 4'), (5, 'Cercle 5')], null=True, verbose_name='Ateneu / Cercle'),
        ),
    ]
