# Generated by Django 3.2.9 on 2022-03-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0055_activity_circle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date_start'], 'verbose_name': 'sessió', 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='cofunding',
            options={'ordering': ['name'], 'verbose_name': 'cofinançadora', 'verbose_name_plural': 'cofinançadores'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-date_start'], 'verbose_name': 'acció', 'verbose_name_plural': 'accions'},
        ),
        migrations.AlterModelOptions(
            name='courseplace',
            options={'ordering': ['name'], 'verbose_name': 'lloc'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name': 'entitat', 'verbose_name_plural': 'entitats'},
        ),
        migrations.AlterModelOptions(
            name='strategicline',
            options={'ordering': ['name'], 'verbose_name': 'línia estratègica', 'verbose_name_plural': 'línies estratègiques'},
        ),
    ]
