# Generated by Django 3.2.14 on 2022-07-21 14:28

import apps.cc_users.managers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cc_courses', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'població',
                'verbose_name_plural': 'poblacions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tagulous_User_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="la durada ha estat l'adequada?")),
                ('hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='els horaris han estat adequats?')),
                ('information', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Informació necessària per fer l'activitat")),
                ('on_schedule', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="S'han complert les dates, horaris, etc...")),
                ('included_resources', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Materials de suport facilitats')),
                ('space_adequation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Els espais han estat adequats (sales, aules, plataforma digital...) ')),
                ('contents', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Els continguts han estat adequats')),
                ('methodology_fulfilled_objectives', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='La metodologia ha estat coherent amb els objectius ')),
                ('methodology_better_results', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='La metodologia ha permès obtenir millors resultats')),
                ('participation_system', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='el sistema de participació i resolució de dubtes ha estat adequat?')),
                ('teacher_has_knowledge', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha mostrat coneixements i experiència sobre el tema?')),
                ('teacher_resolved_doubts', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha aconseguit resoldre els problemes i dubtes que s’ha plantejat?')),
                ('teacher_has_communication_skills', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='el professional ha mostrat competències comunicatives?')),
                ('expectations_satisfied', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha satisfet les meves expectatives')),
                ('adquired_new_tools', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='He incorporat eines per aplicar a nous projectes')),
                ('met_new_people', models.BooleanField(null=True, verbose_name="M'ha permès conèixer persones afins")),
                ('wanted_start_cooperative', models.BooleanField(null=True, verbose_name="Abans del curs, teníeu ganes/necessitats d'engegar algun projecte cooperatiu")),
                ('wants_start_cooperative_now', models.BooleanField(null=True, verbose_name='I després?')),
                ('general_satisfaction', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Grau de satisfacció general')),
                ('also_interested_in', models.TextField(blank=True, null=True, verbose_name="De quins altres temes t'interessaria rebre formació?")),
                ('heard_about_it', models.TextField(blank=True, null=True, verbose_name="com us heu assabentat d'aquesta activitat?")),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Vols comentar alguna cosa més?')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='cc_courses.activity')),
            ],
            options={
                'verbose_name': 'enquesta de valoració',
                'verbose_name_plural': 'enquestes de valoració',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correu electrònic')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('fake_email', models.BooleanField(default=False, help_text='Marca aquesta casella si el correu és inventat, i desmarca-la si mai el canvieu pel correu real. Ens ajudarà a mantenir la base de dadesneta.', verbose_name='e-mail inventat')),
                ('username', models.CharField(max_length=150, null=True, verbose_name="nom d'usuari/a")),
                ('surname2', models.CharField(blank=True, max_length=50, null=True, verbose_name='segon cognom')),
                ('id_number', models.CharField(max_length=11, null=True, verbose_name='DNI/NIE/Passaport')),
                ('cannot_share_id', models.BooleanField(default=False, verbose_name="Si degut a la teva situació legal et suposa un inconvenient indicar el DNI, deixa'l en blanc i marca aquesta casella")),
                ('gender', models.CharField(blank=True, choices=[('OTHER', 'Altre'), ('FEMALE', 'Dona'), ('MALE', 'Home')], max_length=10, null=True, verbose_name='gènere')),
                ('birth_place', models.TextField(blank=True, choices=[('BARCELONA', 'Barcelona'), ('CATALUNYA', 'Catalunya'), ('ESPANYA', 'Espanya'), ('OTHER', 'Altre')], null=True, verbose_name='lloc de naixement')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='data de naixement')),
                ('district', models.TextField(blank=True, choices=[('CV', 'Ciutat Vella'), ('EX', 'Eixample'), ('HG', 'Horta-Guinardó'), ('LC', 'Les Corts'), ('NB', 'Nou Barris'), ('SA', 'Sant Andreu'), ('SM', 'Sant Martí'), ('ST', 'Sants-Montjuïc'), ('SS', 'Sarrià-Sant Gervasi'), ('GR', 'Gràcia')], null=True, verbose_name='districte')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='adreça')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='telèfon')),
                ('educational_level', models.TextField(blank=True, choices=[('MASTER', 'Màster / Postgrau'), ('HIGH_SCHOOL', 'Secundària'), ('WITHOUT_STUDIES', 'Sense estudis'), ('FP', 'Formació professional'), ('UNIVERSITY', 'Estudis universitaris'), ('ELEMENTARY_SCHOOL', 'Primària')], null=True, verbose_name="nivell d'estudis")),
                ('employment_situation', models.TextField(blank=True, choices=[('SELF_EMPLOYED', 'En actiu per compte propi'), ('UNEMPLOYMENT_BENEFIT_RECEIVER', 'Perceptora de prestacions socials'), ('UNEMPLOYMENT_BENEFIT_REQUESTED', "Demandant d'ocupació"), ('EMPLOYED_WORKER', 'En actiu per compte aliè')], null=True, verbose_name='situació laboral')),
                ('discovered_us', models.TextField(blank=True, choices=[('INTERNET', 'Per internet i xarxes socials'), ('FRIEND', "A través d'un conegut"), ('PREVIOUS_ACTIVITY', "Per una activitat de l'ateneu"), ('OTHER', 'Altres')], null=True, verbose_name='com ens has conegut')),
                ('project_involved', models.CharField(blank=True, max_length=240, null=True, verbose_name="si participes a un projecte cooperatiu o de l'ESS, indica'ns-el")),
                ('cooperativism_knowledge', models.TextField(blank=True, help_text='Tens coneixements / formació / experiència en cooperativisme? Quina? Cursos realitzats?', null=True, verbose_name='coneixements previs')),
                ('authorize_communications', models.BooleanField(default=False, verbose_name='autoritza comunicació publicitària')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Prioritza les etiquetes que apareixen auto-completades. Si escrius una etiqueta amb un espai creurà que son dues etiquetes, per evitar-ho escriu-la entre cometes dobles, "etiqueta amb espais".', to='coopolis.Tagulous_User_tags', verbose_name='etiquetes')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.town', verbose_name='població actual')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'persones',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.cc_users.managers.CCUserManager()),
            ],
        ),
    ]
