# Generated by Django 3.2.14 on 2022-11-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cc_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="la durada ha estat l'adequada?")),
                ('hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='els horaris han estat adequats?')),
                ('information', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Informació necessària per fer l'activitat")),
                ('on_schedule', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="S'han complert les dates, horaris, etc...")),
                ('included_resources', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Materials de suport facilitats')),
                ('space_adequation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Els espais han estat adequats (sales, aules, plataforma digital...) ')),
                ('contents', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Els continguts han estat adequats')),
                ('methodology_fulfilled_objectives', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='La metodologia ha estat coherent amb els objectius ')),
                ('methodology_better_results', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='La metodologia ha permès obtenir millors resultats')),
                ('participation_system', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='el sistema de participació i resolució de dubtes ha estat adequat?')),
                ('teacher_has_knowledge', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha mostrat coneixements i experiència sobre el tema?')),
                ('teacher_resolved_doubts', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha aconseguit resoldre els problemes i dubtes que s’ha plantejat?')),
                ('teacher_has_communication_skills', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='el professional ha mostrat competències comunicatives?')),
                ('expectations_satisfied', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha satisfet les meves expectatives')),
                ('adquired_new_tools', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='He incorporat eines per aplicar a nous projectes')),
                ('met_new_people', models.BooleanField(null=True, verbose_name="M'ha permès conèixer persones afins")),
                ('wanted_start_cooperative', models.BooleanField(null=True, verbose_name="Abans del curs, teníeu ganes/necessitats d'engegar algun projecte cooperatiu")),
                ('wants_start_cooperative_now', models.BooleanField(null=True, verbose_name='I després?')),
                ('general_satisfaction', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Grau de satisfacció general')),
                ('also_interested_in', models.TextField(blank=True, null=True, verbose_name="De quins altres temes t'interessaria rebre formació?")),
                ('heard_about_it', models.TextField(blank=True, null=True, verbose_name="com us heu assabentat d'aquesta activitat?")),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Vols comentar alguna cosa més?')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='cc_courses.activity')),
            ],
            options={
                'verbose_name': 'enquesta de valoració',
                'verbose_name_plural': 'enquestes de valoració',
            },
        ),
    ]
