# Generated by Django 2.1.3 on 2019-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0002_auto_20190311_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'verbose_name': 'persona', 'verbose_name_plural': 'persones'},
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='subsidy_period',
            field=models.CharField(blank=True, choices=[('2017', '2016-2017'), ('2018', '2017-2018'), ('2019', '2018-2019')], default=2019, max_length=4, null=True, verbose_name='convocatòria'),
        ),
    ]
