# Generated by Django 2.1.3 on 2019-05-31 10:48

from django.db import migrations


def copy_partners_form_stage_to_project(apps, schema_editor):
    projectstage_obj = apps.get_model('coopolis', 'ProjectStage')
    for project_stage in projectstage_obj.objects.all():
        project = project_stage.project
        for partner in project_stage.involved_partners.all():
            project.partners.add(partner)
            print("Projecte " + project.name + ", afegint partner: " + partner.first_name)


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0007_project_partners'),
    ]

    operations = [
        migrations.RunPython(copy_partners_form_stage_to_project),
    ]
