# Generated by Django 2.1.3 on 2019-07-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0016_auto_20190724_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.TextField(blank=True, choices=[('CV', 'Ciutat Vella'), ('EX', 'Eixample'), ('HG', 'Horta-Guinardó'), ('LC', 'Les Corts'), ('NB', 'Nou Barris'), ('SA', 'Sant Andreu'), ('SM', 'Sant Martí'), ('ST', 'Sants-Montjuïc'), ('SS', 'Sarrià-Sant Gervasi'), ('GR', 'Gràcia')], null=True, verbose_name='districte'),
        ),
    ]
