# Generated by Django 2.0.13 on 2019-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0017_auto_20190724_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='subaxis',
            field=models.CharField(blank=True, choices=[(None, 'Selecciona un eix')], help_text="Correspon a 'Tipus d'acció' a la justificació.", max_length=2, null=True, verbose_name='sub-eix'),
        ),
    ]
