# Generated by Django 2.0.13 on 2019-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0020_auto_20190802_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discovered_us',
            field=models.TextField(blank=True, choices=[('INTERNET', 'Per internet i xarxes socials'), ('FRIEND', "A través d'un conegut"), ('PREVIOUS_ACTIVITY', "Per una activitat de l'ateneu"), ('OTHER', 'Altres')], null=True, verbose_name='com ens has conegut'),
        ),
    ]
