# Generated by Django 2.0 on 2019-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0021_auto_20190812_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=11, null=True, verbose_name='DNI/NIE/Passaport'),
        ),
    ]
