# Generated by Django 2.0 on 2019-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0022_auto_20191022_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='subsidy_period',
            field=models.CharField(blank=True, choices=[('2017', '2016-2017'), ('2018', '2017-2018'), ('2019', '2018-2019'), ('2020', '2019-2020')], default=2019, max_length=4, null=True, verbose_name='convocatòria'),
        ),
    ]
