# Generated by Django 2.1.3 on 2019-06-03 15:27

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def add_group_permissions(apps, schema_editor):

    # gestió de sales
    group, created = Group.objects.get_or_create(name="Afegir o modificar Sales")
    if created:
        add_thing = Permission.objects.filter(
            codename__in=['add_room', 'change_room', 'delete_room', ]
        )
        group.permissions.set(add_thing)
        group.save()
        print('Grup de permisos de gestió de Sales creat.')

    # gestió de reserves de sales
    group, created = Group.objects.get_or_create(name="Fer i modificar reserves d'espais")
    if created:
        add_thing = Permission.objects.filter(
            codename__in=['add_reservation', 'change_reservation', 'delete_reservation', ]
        )
        group.permissions.set(add_thing)
        group.save()
        print('Grup de permisos de gestió de Reserves creat.')


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0023_auto_20191031_1350'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
