# Generated by Django 2.0 on 2019-11-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0026_auto_20191119_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'derivació',
                'verbose_name_plural': 'derivacions',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='derivation_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de derivació'),
        ),
        migrations.AddField(
            model_name='project',
            name='derivation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Derivation'),
        ),
    ]
