# Generated by Django 2.2.7 on 2020-01-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0031_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(choices=[('A', 'Altres'), ('C', 'Comunicació i tecnologia'), ('F', 'Finances'), ('O', 'Oci'), ('H', 'Habitatge'), ('L', 'Logística'), ('E', 'Educació'), ('CU', 'Cultura'), ('S', 'Assessorament'), ('M', 'Alimentació'), ('U', 'Cures'), ('R', 'Roba')], max_length=2),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='subaxis',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('A1', 'A.1 Reunions de la taula territorial'), ('A2', 'A.2 Diagnosi entitats socials del territori'), ('A3', 'A.3 Elaboració catàleg bones pràctiques'), ('A4', "A.4 Jornades per presentar experiències de bones pràctiques o jornades sectorials i/o d'interès per al territori"), ('A5', 'A.5 Assistència a fires, actes per visibilitzar el programa'), ('A6', 'A.6 Publicitat en mitjans de comunicació.  Web del programa'), ('A7', 'A.7 Altres'), ('B1', 'B.1 Accions de suport a la inserció laboral i a la creació de cooperatives i societats laborals (concursos de projectes cooperatius o altres accions)'), ('B2', 'B.2 Tallers sensibilització o dinamització'), ('B3', 'B.3 Acompanyament a empreses i entitats'), ('B4', 'B.4 Altres'), ('C1', 'C.1 Tallers de dinamització adreçats al teixit associatiu i a empreses'), ('C2', "C.2 Tallers de dinamització adreçats a professionals que s'agrupen per prestar serveis de manera conjunta"), ('C3', 'C.3 Altres'), ('D1', 'D.1 Accions de difusió'), ('D2', 'D.2 Activitats de sensibilització o dinamització.'), ('D3', 'D.3 Acompanyament individualitzat'), ('D4', 'D.4 Altres'), ('E1', 'E.1 Tallers a joves'), ('E2', 'E.2 Atenció individual professorat'), ('E3', 'E.3 Complementàries (recursos, eines, productes, publicacions sectorials pròpies )'), ('E4', 'E.4 Altres'), ('F1', "F.1 Pla d'actuació"), ('F2', "F.2 Tallers de creació de cooperatives o societats laborals, o transformació d'associacions, altres entitats"), ('F3', 'F.3 Altres')], help_text="Correspon a 'Tipus d'acció' a la justificació.", max_length=2, null=True, verbose_name='sub-eix'),
        ),
    ]
