# Generated by Django 2.2.7 on 2020-01-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0011_restore_transfered_field_name'),
        ('coopolis', '0032_auto_20200116_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='subsidy_period_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.SubsidyPeriod'),
        ),
    ]
