# Generated by Django 2.2.7 on 2020-01-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0038_employmentinsertion_subsidy_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinsertion',
            name='subsidy_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.SubsidyPeriod', verbose_name='convocatòria'),
        ),
    ]
