# Generated by Django 2.2.7 on 2020-01-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0039_auto_20200121_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='subsidy_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.SubsidyPeriod', verbose_name='convocatòria'),
        ),
    ]
