# Generated by Django 2.2.7 on 2020-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0043_auto_20200402_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='stage_type',
            field=models.CharField(choices=[('1', '00 Nova creació - acollida'), ('2', '01 Nova creació - procés'), ('6', '02 Nova creació - constitució'), ('7', '03 Consolidació - 1a acollida'), ('8', '04 Consolidació - acompanyament'), ('9', '05 Incubació'), ('10', '06 Crisi Covid')], default=1, max_length=2, verbose_name="tipus d'acompanyament"),
        ),
    ]
