# Generated by Django 2.2.7 on 2020-04-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0045_user_authorize_communications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagesbyaxis',
            options={'ordering': ['axis', 'subaxis', 'entity', 'date_start'], 'verbose_name': 'acompanyament', 'verbose_name_plural': 'Acompanyaments per Eix'},
        ),
        migrations.RenameField(
            model_name='projectstage',
            old_name='organizer',
            new_name='entity',
        ),
    ]
