# Generated by Django 2.2.7 on 2020-04-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0031_auto_20200120_1943'),
        ('coopolis', '0046_auto_20200406_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='stage_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Organizer', verbose_name='organitzadora'),
        ),
    ]
