# Generated by Django 2.2.7 on 2020-04-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0047_projectstage_stage_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Town', verbose_name='població'),
        ),
    ]
