# Generated by Django 2.2.7 on 2020-05-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0049_user_groups_enrollments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'persona', 'verbose_name_plural': 'persones'},
        ),
        migrations.AlterField(
            model_name='project',
            name='motivation',
            field=models.CharField(blank=True, choices=[('COOPERATIVISM_EDUCATION', 'Formació en cooperativisme'), ('COOPERATIVE_CREATION', "Constitució d'una cooperativa"), ('TRANSFORM_FROM_ASSOCIATION', "Transformació d'associació a cooperativa"), ('TRANSFORM_FROM_SCP', 'Transformació de SCP a cooperativa'), ('ENTERPRISE_RELIEF', 'Relleu empresarial'), ('CONSOLIDATION', 'Consolidació'), ('OTHER', 'Altres')], max_length=50, null=True, verbose_name='petició inicial'),
        ),
    ]
