# Generated by Django 2.2.7 on 2020-06-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0052_mail_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsFollowUp',
            fields=[
            ],
            options={
                'verbose_name': "Seguiment d'acompanyament",
                'verbose_name_plural': "Seguiment d'acompanyaments",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coopolis.projectstage',),
        ),
    ]
