# Generated by Django 2.2.7 on 2020-06-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0014_auto_20200616_1407'),
        ('coopolis', '0058_auto_20200612_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subsidy_period',
            field=models.ForeignKey(help_text="OPCIONAL. En cas que el projecte s'hagi constituït en una convocatòria posterior a l'ultima intervenció de l'ateneu, podeu indicar-ho aquí, per tal que aparegui a l'informe de Projectes Constituïts. Aquest camp NO farà aparèixer el projecte a l'excel de justificació (per aparèixer a l'excel cal crear una Justificació d'Acompanyament", null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.SubsidyPeriod', verbose_name='convocatòria de la constitució'),
        ),
    ]
