# Generated by Django 2.2.7 on 2020-07-15 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0041_auto_20200714_1704'),
        ('coopolis', '0061_auto_20200714_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('duration', models.PositiveSmallIntegerField(verbose_name="la durada ha estat l'adequada?")),
                ('hours', models.PositiveSmallIntegerField(verbose_name='els horaris han estat adequats?')),
                ('information', models.PositiveSmallIntegerField(verbose_name="Informació necessària per fer l'activitat")),
                ('on_schedule', models.PositiveSmallIntegerField(verbose_name="S'han complert les dates, horaris, etc...")),
                ('included_resources', models.PositiveSmallIntegerField(verbose_name='Materials de suport facilitats')),
                ('space_adequation', models.PositiveSmallIntegerField(verbose_name='Els espais han estat adequats (sales,aules...) ')),
                ('contents', models.PositiveSmallIntegerField(verbose_name='Els continguts han estat adequats')),
                ('methodology_fulfilled_objectives', models.PositiveSmallIntegerField(verbose_name='La metodologia ha estat coherent amb els objectius ')),
                ('methodology_better_results', models.PositiveSmallIntegerField(verbose_name='La metodologia ha permès obtenir millors resultats')),
                ('teacher_has_knowledge', models.PositiveSmallIntegerField(verbose_name='Ha mostrat coneixements i experiència sobre el tema?')),
                ('teacher_resolved_doubts', models.PositiveSmallIntegerField(verbose_name='Ha aconseguit resoldre els problemes i dubtes que s’ha plantejat?')),
                ('expectations_satisfied', models.PositiveSmallIntegerField(verbose_name='Ha satisfet les meves expectatives')),
                ('adquired_new_tools', models.PositiveSmallIntegerField(verbose_name='He incorporat eines per aplicar a nous projectes')),
                ('met_new_people', models.NullBooleanField(verbose_name="M'ha permès conèixer persones afins")),
                ('wanted_start_cooperative', models.NullBooleanField(verbose_name="Abans del curs, teníeu ganes/necessitats d'engegar algun projecte cooperatiu")),
                ('wants_start_cooperative_now', models.NullBooleanField(verbose_name='I després?')),
                ('general_satisfaction', models.PositiveSmallIntegerField(verbose_name='Grau de satisfacció general')),
                ('also_interested_in', models.TextField(verbose_name="De quins altres temes t'interessaria rebre formació?")),
                ('comments', models.TextField(verbose_name='Vols comentar alguna cosa més?')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='cc_courses.Activity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enquesta de valoració',
                'verbose_name_plural': 'enquestes de valoració',
            },
        ),
    ]
