# Generated by Django 2.2.7 on 2020-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0062_activitypoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypoll',
            name='adquired_new_tools',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='He incorporat eines per aplicar a nous projectes'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='also_interested_in',
            field=models.TextField(blank=True, null=True, verbose_name="De quins altres temes t'interessaria rebre formació?"),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Vols comentar alguna cosa més?'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='contents',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Els continguts han estat adequats'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="la durada ha estat l'adequada?"),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='expectations_satisfied',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha satisfet les meves expectatives'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='general_satisfaction',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Grau de satisfacció general'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='els horaris han estat adequats?'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='included_resources',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Materials de suport facilitats'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='information',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Informació necessària per fer l'activitat"),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='methodology_better_results',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='La metodologia ha permès obtenir millors resultats'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='methodology_fulfilled_objectives',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='La metodologia ha estat coherent amb els objectius '),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='on_schedule',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="S'han complert les dates, horaris, etc..."),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='space_adequation',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Els espais han estat adequats (sales,aules...) '),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='teacher_has_knowledge',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha mostrat coneixements i experiència sobre el tema?'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='teacher_resolved_doubts',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ha aconseguit resoldre els problemes i dubtes que s’ha plantejat?'),
        ),
        migrations.AddConstraint(
            model_name='activitypoll',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_answer'),
        ),
    ]
