# Generated by Django 2.2.7 on 2020-07-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0063_auto_20200715_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypoll',
            name='heard_about_it',
            field=models.TextField(blank=True, null=True, verbose_name="com us heu assabentat d'aquesta activitat?"),
        ),
        migrations.AddField(
            model_name='activitypoll',
            name='participation_system',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='el sistema de participació i resolució de dubtes ha estat adequat?'),
        ),
        migrations.AddField(
            model_name='activitypoll',
            name='teacher_has_communication_skills',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='el professional ha mostrat competències comunicatives?'),
        ),
        migrations.AlterField(
            model_name='activitypoll',
            name='space_adequation',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Els espais han estat adequats (sales, aules, plataforma digital...) '),
        ),
    ]
