# Generated by Django 2.2.7 on 2020-10-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0071_auto_20200915_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StagesByAxis',
        ),
    ]
