# Generated by Django 2.2.7 on 2020-10-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0072_delete_stagesbyaxis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinsertion',
            name='contract_type',
            field=models.CharField(choices=[('autonom', 'Autònom -RETA-'), ('general_cpropi', 'Règim general - compte propi'), ('general_calie', 'Règim general - compte aliè')], max_length=50, null=True, verbose_name='tipus de contracte'),
        ),
    ]
