# Generated by Django 2.2.7 on 2020-10-08 13:52

from django.db import migrations


def clean_contract_type(apps, schema_editor):
    print('')
    insertions_model = apps.get_model('coopolis', 'EmploymentInsertion')
    insertions_model.objects.all().update(contract_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0073_auto_20201008_1552'),
    ]

    operations = [
        migrations.RunPython(clean_contract_type),
    ]
