# Generated by Django 2.2.7 on 2021-03-29 10:19

from django.db import migrations


def migrate_to_stage_subtype(apps, schema_editor):
    print('')
    subtype_model = apps.get_model('coopolis', 'StageSubtype')
    stage_model = apps.get_model('coopolis', 'ProjectStage')

    sub_acollida = subtype_model.objects.create(
        name='Acollida'
    )
    sub_proces = subtype_model.objects.create(
        name='Procés'
    )
    sub_constitucio = subtype_model.objects.create(
        name='Constitució'
    )
    sub_acompanyament = subtype_model.objects.create(
        name='Acompanyament'
    )

    stage_model.objects.filter(stage_type=1).update(
        stage_type=11,
        stage_subtype=sub_acollida
    )
    stage_model.objects.filter(stage_type=2).update(
        stage_type=11,
        stage_subtype=sub_proces
    )
    stage_model.objects.filter(stage_type=6).update(
        stage_type=11,
        stage_subtype=sub_constitucio
    )
    stage_model.objects.filter(stage_type=7).update(
        stage_type=12,
        stage_subtype=sub_acollida
    )
    stage_model.objects.filter(stage_type=8).update(
        stage_type=12,
        stage_subtype=sub_acompanyament
    )
    print("Acompanyaments: migració a Subtipus feta.")


def stage_date_start_normalization(apps, schema_editor):
    print('')
    stage_model = apps.get_model('coopolis', 'ProjectStage')

    stages = stage_model.objects.filter(date_start=None)

    for stage in stages:
        stage.date_start = stage.subsidy_period.date_start
        stage.save()
        print(f"Acompanyament sense data actualitzat: {stage} ")
    print("Acompanyaments: normalització de date_start acabada.")


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0081_auto_20210329_1145'),
    ]

    operations = [
        migrations.RunPython(migrate_to_stage_subtype),
        migrations.RunPython(stage_date_start_normalization),
    ]
