# Generated by Django 2.2.7 on 2021-05-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0050_auto_20210505_1433'),
        ('coopolis', '0084_auto_20210505_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinsertion',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='alta baixa social'),
        ),
        migrations.AddField(
            model_name='employmentinsertion',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Organizer', verbose_name='organitzadora'),
        ),
    ]
