# Generated by Django 2.2.7 on 2021-09-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0085_auto_20210513_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinsertion',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='baixa seg. social'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='date_start',
            field=models.DateField(auto_now_add=True, verbose_name='data creació acompanyament'),
        ),
        migrations.AlterField(
            model_name='projectstagesession',
            name='hours',
            field=models.FloatField(blank=True, help_text='Camp necessari per la justificació.', null=True, verbose_name="número d'hores"),
        ),
    ]
