# Generated by Django 3.2.9 on 2021-12-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0089_datamigration_mail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='service',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Cap'), (10, 'Servei de mapatge i diagnosi'), (20, 'Servei de Divulgació, Sensibilització i Generació de Coneixement.'), (30, "Servei de Formació per a la promoció, creació i consolidació de cooperatives i projectes de l'ESS."), (40, "Servei d'Acompanyament per la creació i consolidació de cooperatives i projectes de l'ESS."), (50, 'Servei de Facilitació de la Intercooperació, treball en xarxa i dinamització territorial.'), (60, "Punt d'informació sobre l'ESS.")], null=True, verbose_name='Servei'),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.town', verbose_name='població actual'),
        ),
    ]
