# Generated by Django 3.2.9 on 2021-12-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0091_auto_20211222_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstage',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='projectstage',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='projectstage',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='projectstage',
            name='scanned_signatures',
        ),
    ]
