# Generated by Django 3.2.9 on 2022-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0095_datamigration_organizers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentinsertion',
            name='organizer',
        ),
        migrations.AddField(
            model_name='employmentinsertion',
            name='circle',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Cap'), (0, 'Ateneu'), (1, 'Cercle 1'), (2, 'Cercle 2'), (3, 'Cercle 3'), (4, 'Cercle 4'), (5, 'Cercle 5')], null=True, verbose_name='Ateneu / Cercle'),
        ),
    ]
