# Generated by Django 2.2.7 on 2020-08-07 07:45

from django.db import migrations


def populate_mail_templates(apps, schema_editor):
    print('')
    mail_model = apps.get_model('mailing_manager', 'Mail')

    obj, created = mail_model.objects.update_or_create(
        text_identifier='EMAIL_PROJECT_REQUEST_CONFIRMATION',
        defaults={
            'text_identifier': 'EMAIL_PROJECT_REQUEST_CONFIRMATION',
            'subject': "Nova sol·licitud d'acompanyament: {projecte_nom}",
            'body': """<p><strong>Confirmació de sol·licitud d'acompanyament 
pel projecte {projecte_nom}</strong></p>
<p style="padding-top: 20px">En els propers dies una persona de l'equip de 
l'ateneu cooperatiu es posarà en contacte amb tu per parlar dels propers 
passos.</p>
<p style="padding-top: 20px">Per consultar i modificar la fitxa del projecte 
accedeix a <a href="{url_backoffice}">l'aplicació dels serveis de l'ateneu</a>.
</p>
            """,
            'default_template_path': 'emails/front_single_text.html'
        },
    )
    print('EMAIL_PROJECT_REQUEST_CONFIRMATION template updated.')


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0096_auto_20220112_1451'),
    ]

    operations = [
        migrations.RunPython(populate_mail_templates),
    ]
