# Generated by Django 3.2.9 on 2022-04-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0098_auto_20220325_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='sub_service',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Cap'), (101, "Taula territorial per l'articulació conjunta de l'economia social amb els diversos actors."), (102, "Elaboració d'un catàleg bones pràctiques."), (103, 'Organització de jornades per visibilitzar experiències, presència als mitjans de comunicació locals, assistència a fires, actes i premis, trobades sectorials, col·laboracions amb altres iniciatives.'), (199, "Altres accions dins del servei de mapeig i diagnosi (si s'escau desenvolupeu a la memòria)"), (201, "Campanya de Comunicació i difusió a col·lectius d'especial atenció. Materials específic de difusió sobre la fórmula cooperativa."), (202, 'Tallers dirigits a joves estudiants de cicles formatius presencials o virtuals .'), (203, 'Accions per a la creació de diferents classes de cooperatives (concursos i tallers sensibilització)'), (204, 'Diagnosi sobre les mancances i oportunitats socioeconòmiques i identificació de les empreses participants.'), (205, "Sessions col·lectives i d'acompanyament expert individual."), (299, "Altres accions dins del servei de divulgació, sensibilitzacio i generació de coneixement (si s'escau desenvolupeu a la memòria)"), (301, 'Activitats formatives i informatives.'), (302, 'Tallers de formació bàsica a persones emprenedores interessades en la fòrmula cooperativa .'), (303, 'Sessions col·lectives'), (304, 'Acompanyament expert'), (305, 'Tallers de sensibilització o dinamització adreçada al teixit associatiu, empreses o professionals.'), (399, "Altres accions dins del servei de formació (si s'escau desenvolupeu a la memòria)"), (401, "Assessorament a mida per a la creació de cooperatives i altres organitzacions d'ESS"), (402, 'Acompanyament a la consolidació i creixement de cooperatives existents'), (403, "Acompanyament a la transformació d'empreses"), (404, 'Campanya de comunicació i difusió'), (405, 'Accions de sensibilització o dinamització'), (499, "Altres accions dins del servei d'acompanyament (si s'escau desenvolupeu a la memòria)"), (501, "Generar espais d'intercooperació i treball en xarxa dins del territori, intercooperació local, creació d'espais i grups d'intercooperació"), (502, "Incorporació d'empreses a l'ateneu cooperatiu i assemblea"), (503, 'Treball en xarxa amb altres ateneus: assistir a reunions i col·laborar en iniciatives conjuntes.'), (599, "Altres accions dins del servei de facilitació (si s'escau desenvolupeu a la memòria)"), (601, 'Espai físic per proporcionar informació sobre ESS a diferents públics'), (602, "Difusió del Punt o punts d'informació")], null=True, verbose_name='Sub-servei'),
        ),
    ]
