# Generated by Django 2.2.7 on 2020-01-20 12:38
#
# We included `data` in the filename to make it easier to identify as a migration that should not be deleted when
# recreating migrations.

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        UnaccentExtension(),
    ]
