# Generated by Django 3.2.14 on 2024-04-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_data_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='stage_type',
            field=models.CharField(choices=[('11', 'Creació'), ('12', 'Consolidació'), ('13', 'Creixement')], default=1, max_length=2, verbose_name="tipus d'acompanyament"),
        ),
    ]
