# Generated by Django 3.2.14 on 2022-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_data_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Barri'),
        ),
    ]
