# Generated by Django 3.2.14 on 2022-11-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_neighborhood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsConstituted',
        ),
        migrations.DeleteModel(
            name='ProjectsFollowUp',
        ),
    ]
