# Generated by Django 3.2.14 on 2024-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20240502_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cif',
        ),
        migrations.AddField(
            model_name='employmentinsertion',
            name='entity_sector',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'Agricultura i ramaderia'), (20, 'Alimentació i consum'), (30, 'Atenció a les persones i cures (criança, col·lectius vulnerables...)'), (40, 'Comerç (just, proximitat, etc.)'), (50, 'Cultura i oci (lleure, esport, esdeveniments...)'), (60, 'Economia circular (reciclatge, recuperació i reutilització de residus)'), (70, 'Educació / Formació'), (80, 'Feminismes LGTBIQ+'), (90, 'Finançament i assegurances (micromecenatge, finances ètiques, ....)'), (100, "Gestió i conservació de l'espai natural (gestió de residus,"), (110, 'Hosteleria i restauració'), (120, 'Industria'), (130, 'Joventut'), (140, 'Logística i mobilitat (transports, bancs de recursos, emmagatzematge...)'), (150, 'Màrqueting i comunicació (xarxes, audiovisual, arts gràfiques, disseny...)'), (160, 'Ruralitats (despoblament, relleu,...)'), (170, 'Salut (mental, sexualitat, ...)'), (180, "Serveis d'assessoria i gestoria"), (190, 'Tecnologies i innovació'), (200, 'Transició energètica / recursos naturals'), (210, 'Turisme (rural, sostenible,...)'), (220, 'Urbanisme i habitatge (arquitectura, rehabilitació, masoveria, ...)')], null=True, verbose_name="sector de l'entitat"),
        ),
        migrations.AddField(
            model_name='project',
            name='annuity',
            field=models.SmallIntegerField(blank=True, choices=[(24, '2024-25'), (25, '2025-26')], null=True, verbose_name='anualitat'),
        ),
        migrations.AddField(
            model_name='project',
            name='entity_cif',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='NIF entitat'),
        ),
        migrations.AddField(
            model_name='project',
            name='entity_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='nom entitat'),
        ),
        migrations.AddField(
            model_name='project',
            name='entity_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Associació'), (2, 'Cooperativa')], null=True, verbose_name="tipus d'entitat"),
        ),
        migrations.AddField(
            model_name='project',
            name='project_sector',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'Agricultura i ramaderia'), (20, 'Alimentació i consum'), (30, 'Atenció a les persones i cures (criança, col·lectius vulnerables...)'), (40, 'Comerç (just, proximitat, etc.)'), (50, 'Cultura i oci (lleure, esport, esdeveniments...)'), (60, 'Economia circular (reciclatge, recuperació i reutilització de residus)'), (70, 'Educació / Formació'), (80, 'Feminismes LGTBIQ+'), (90, 'Finançament i assegurances (micromecenatge, finances ètiques, ....)'), (100, "Gestió i conservació de l'espai natural (gestió de residus,"), (110, 'Hosteleria i restauració'), (120, 'Industria'), (130, 'Joventut'), (140, 'Logística i mobilitat (transports, bancs de recursos, emmagatzematge...)'), (150, 'Màrqueting i comunicació (xarxes, audiovisual, arts gràfiques, disseny...)'), (160, 'Ruralitats (despoblament, relleu,...)'), (170, 'Salut (mental, sexualitat, ...)'), (180, "Serveis d'assessoria i gestoria"), (190, 'Tecnologies i innovació'), (200, 'Transició energètica / recursos naturals'), (210, 'Turisme (rural, sostenible,...)'), (220, 'Urbanisme i habitatge (arquitectura, rehabilitació, masoveria, ...)')], null=True, verbose_name='sector activitat'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='agents_involved',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='agents implicats'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='communality_role',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Participant / Assistent (rol passiu)'), (2, 'Organitzador / Col·laborador (rol actiu)')], null=True, verbose_name='rol comunalitat'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='networking',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Conjunta')], null=True, verbose_name='treball en xarxa'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='project_sector',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'Agricultura i ramaderia'), (20, 'Alimentació i consum'), (30, 'Atenció a les persones i cures (criança, col·lectius vulnerables...)'), (40, 'Comerç (just, proximitat, etc.)'), (50, 'Cultura i oci (lleure, esport, esdeveniments...)'), (60, 'Economia circular (reciclatge, recuperació i reutilització de residus)'), (70, 'Educació / Formació'), (80, 'Feminismes LGTBIQ+'), (90, 'Finançament i assegurances (micromecenatge, finances ètiques, ....)'), (100, "Gestió i conservació de l'espai natural (gestió de residus,"), (110, 'Hosteleria i restauració'), (120, 'Industria'), (130, 'Joventut'), (140, 'Logística i mobilitat (transports, bancs de recursos, emmagatzematge...)'), (150, 'Màrqueting i comunicació (xarxes, audiovisual, arts gràfiques, disseny...)'), (160, 'Ruralitats (despoblament, relleu,...)'), (170, 'Salut (mental, sexualitat, ...)'), (180, "Serveis d'assessoria i gestoria"), (190, 'Tecnologies i innovació'), (200, 'Transició energètica / recursos naturals'), (210, 'Turisme (rural, sostenible,...)'), (220, 'Urbanisme i habitatge (arquitectura, rehabilitació, masoveria, ...)')], null=True, verbose_name='sector del projecte'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='types',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Acompanyament'), (2, 'Acte'), (3, 'Cartografia /mapeig'), (4, 'Cicle'), (5, 'Entrevista'), (6, 'Exposició'), (7, 'Festival'), (8, 'Fira'), (9, 'Inauguració'), (10, 'Jornada'), (11, 'Premi'), (12, 'Presentació'), (13, 'Publicació'), (14, 'Punt informació'), (15, 'Reunió'), (16, 'Sessió formativa/ informativa'), (17, 'Taller'), (18, 'Trobada'), (19, 'Trobades assemblea'), (20, 'Visita'), (21, 'Xerrada')], null=True, verbose_name='tipus actuació'),
        ),
    ]
