# Generated by Django 3.2.14 on 2024-07-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0009_alter_activity_course'),
        ('towns', '0002_load_town_fixtures'),
        ('projects', '0006_auto_20240716_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'projecte acompanyat', 'verbose_name_plural': 'projectes acompanyats'},
        ),
        migrations.AddField(
            model_name='projectstage',
            name='course',
            field=models.ForeignKey(help_text="Escriu el nom del projecte i selecciona'l del desplegable. Si no existeix, clica a la lupa i després a 'Crear projecte'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_activities', to='cc_courses.course', verbose_name="Projecte al qual s'engloba"),
        ),
        migrations.AlterField(
            model_name='employmentinsertion',
            name='contract_type',
            field=models.SmallIntegerField(choices=[(1, 'Indefinit'), (5, 'Temporal'), (2, 'Soci/a cooperativa o societat laboral'), (3, 'Autònom')], null=True, verbose_name='tipus de contracte o vinculació'),
        ),
        migrations.AlterField(
            model_name='employmentinsertion',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data baixa SS'),
        ),
        migrations.AlterField(
            model_name='employmentinsertion',
            name='entity_neighborhood',
            field=models.CharField(max_length=50, verbose_name='barri entitat'),
        ),
        migrations.AlterField(
            model_name='employmentinsertion',
            name='entity_sector',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'Agricultura i ramaderia'), (20, 'Alimentació i consum'), (30, 'Atenció a les persones i cures (criança, col·lectius vulnerables...)'), (40, 'Comerç (just, proximitat, etc.)'), (50, 'Cultura i oci (lleure, esport, esdeveniments...)'), (60, 'Economia circular (reciclatge, recuperació i reutilització de residus)'), (70, 'Educació / Formació'), (80, 'Feminismes LGTBIQ+'), (90, 'Finançament i assegurances (micromecenatge, finances ètiques, ....)'), (100, "Gestió i conservació de l'espai natural (gestió de residus,"), (110, 'Hosteleria i restauració'), (120, 'Industria'), (130, 'Joventut'), (140, 'Logística i mobilitat (transports, bancs de recursos, emmagatzematge...)'), (150, 'Màrqueting i comunicació (xarxes, audiovisual, arts gràfiques, disseny...)'), (160, 'Ruralitats (despoblament, relleu,...)'), (170, 'Salut (mental, sexualitat, ...)'), (180, "Serveis d'assessoria i gestoria"), (190, 'Tecnologies i innovació'), (200, 'Transició energètica / recursos naturals'), (210, 'Turisme (rural, sostenible,...)'), (220, 'Urbanisme i habitatge (arquitectura, rehabilitació, masoveria, ...)')], null=True, verbose_name="sector de l'empresa"),
        ),
        migrations.AlterField(
            model_name='employmentinsertion',
            name='entity_town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='towns.town', verbose_name='municipi entitat'),
        ),
        migrations.AlterField(
            model_name='employmentinsertion',
            name='insertion_date',
            field=models.DateField(verbose_name='data alta SS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='towns.town', verbose_name='municipi'),
        ),
        migrations.AlterField(
            model_name='projectstagesession',
            name='hours',
            field=models.FloatField(blank=True, help_text="A la justificació es sumaran les hores de totes les sessions de l'acompanyament.", null=True, verbose_name='Estimació hores dedicació'),
        ),
    ]
