# Generated by Django 3.2.9 on 2022-03-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0005_auto_20211108_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'sala', 'verbose_name_plural': 'sales'},
        ),
    ]
