version: "3.5"

networks:
  develop_comunalitats_network:
    name: develop_comunalitats_network

services:
  # http://127.0.0.1:5012 or http://localhost:5012
  develop_comunalitats_altpirineu:
    restart: on-failure
    container_name: develop_comunalitats_altpirineu
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/altpirineu.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8012 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5012:8012

  # http://127.0.0.1:5004 or http://localhost:5004
  develop_comunalitats_bnord:
    restart: on-failure
    container_name: develop_comunalitats_bnord
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/bnord.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8004 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5004:8004

  # http://127.0.0.1:5007 or http://localhost:5007
  develop_comunalitats_catcentral:
    restart: on-failure
    container_name: develop_comunalitats_catcentral
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/catcentral.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8007 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5007:8007

  # http://127.0.0.1:5002 or http://localhost:5002
  develop_comunalitats_coopcamp:
    restart: on-failure
    container_name: develop_comunalitats_coopcamp
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/coopcamp.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8002 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5002:8002

  # http://127.0.0.1:5003 or http://localhost:5003
  develop_comunalitats_coopmaresme:
    restart: on-failure
    container_name: develop_comunalitats_coopmaresme
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/coopmaresme.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8003 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5003:8003

  # http://127.0.0.1:5001 or http://localhost:5001
  develop_comunalitats_coopolis:
    restart: on-failure
    container_name: develop_comunalitats_coopolis
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/coopolis.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8001 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5001:8001

  # http://127.0.0.1:5008 or http://localhost:5008
  develop_comunalitats_coopsetania:
    restart: on-failure
    container_name: develop_comunalitats_coopsetania
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/coopsetania.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8008 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5008:8008

  # http://127.0.0.1:5010 or http://localhost:5010
  develop_comunalitats_hospitalet:
    restart: on-failure
    container_name: develop_comunalitats_hospitalet
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/hospitalet.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8010 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5010:8010

  # http://127.0.0.1:5005 or http://localhost:5005
  develop_comunalitats_ponentcoopera:
    restart: on-failure
    container_name: develop_comunalitats_ponentcoopera
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/ponentcoopera.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8005 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5005:8005

  # http://127.0.0.1:5011 or http://localhost:5011
  develop_comunalitats_terresebre:
    restart: on-failure
    container_name: develop_comunalitats_terresebre
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/terresebre.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8011 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5011:8011

  # http://127.0.0.1:5009 or http://localhost:5009
  develop_comunalitats_terresgironines:
    restart: on-failure
    container_name: develop_comunalitats_terresgironines
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/terresgironines.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8009 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5009:8009

  # http://127.0.0.1:5006 or http://localhost:5006
  develop_comunalitats_vallesoccidental:
    restart: on-failure
    container_name: develop_comunalitats_vallesoccidental
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/vallesoccidental.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8006 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5006:8006

  # http://127.0.0.1:5006 or http://localhost:5006
  develop_comunalitats_baixllobregat:
    restart: on-failure
    container_name: develop_comunalitats_baixllobregat
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/develop/baixllobregat.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8013 --reload
    volumes:
      - ../src/:/srv
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 5013:8013

  # http://localhost:8080/
#  develop_comunalitats_adminer:
#    container_name: develop_comunalitats_adminer
#    image: adminer
#    ports:
#      - 9876:8080
#    depends_on:
#      - develop_comunalitats_rb
#    networks:
#      - develop_comunalitats_network

  develop_comunalitats_db:
    container_name: develop_comunalitats_db
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../dumps:/dumps
    networks:
      - develop_comunalitats_network
