version: "3.5"

networks:
  develop_comunalitats_network:
    name: develop_comunalitats_network

services:
  # http://localhost:4001
  develop_comunalitat_1:
    restart: on-failure
    container_name: develop_comunalitat_1
    image: codicoop/comunalitats:latest
    env_file: ./settings/develop/comunalitat_1.env
    # The WSGI application name is the django app name you chose when doing django-admin startproject.
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8001 --threads=10
    depends_on:
      - develop_comunalitats_db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    networks:
      - develop_comunalitats_network
    ports:
      - 4001:8001

  # http://localhost:8080/
#  develop_comunalitats_adminer:
#    container_name: develop_comunalitats_adminer
#    image: adminer
#    ports:
#      - 9876:8080
#    depends_on:
#      - develop_comunalitats_rb
#    networks:
#      - develop_comunalitats_network

  develop_comunalitats_db:
    container_name: develop_comunalitats_db
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../dumps:/dumps
    networks:
      - develop_comunalitats_network
