# Generated by Django 2.1.3 on 2019-02-25 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cc_courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled_activities', to=settings.AUTH_USER_MODEL, verbose_name='Inscrites'),
        ),
        migrations.AddField(
            model_name='activity',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.CoursePlace', verbose_name='Lloc'),
        ),
    ]
