# Generated by Django 2.1.3 on 2019-03-11 20:01

from django.db import migrations


def create_entities(apps, schema_editor):
    model = apps.get_model('cc_courses', 'Entity')
    if model.objects.count() > 0:
        print("Entities already populated, skipping migration.")
        return
    model.objects.bulk_create([
        model(name='Ateneu'),
        model(name='Cercle Migracions'),
        model(name='Cercle Incubació'),
        model(name='Cercle Consum')
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0002_auto_20190311_2059'),
    ]

    operations = [
        migrations.RunPython(create_entities),
    ]
