# Generated by Django 2.1.3 on 2019-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0002_auto_20190225_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Dia finalització'),
        ),
    ]
