# Generated by Django 2.1.3 on 2019-02-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0004_auto_20190226_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='axis',
            field=models.TextField(blank=True, choices=[('A', 'Eix A'), ('B', 'Eix B'), ('C', 'Eix C'), ('D', 'Eix D')], help_text='Eix de la convocatòria on es justificarà.', null=True, verbose_name='Eix'),
        ),
    ]
