# Generated by Django 2.1.3 on 2019-03-05 19:34

import cc_courses.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0005_auto_20190227_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=250, null=True, upload_to=cc_courses.models.upload_path),
        ),
    ]
