# Generated by Django 2.1.3 on 2019-03-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0006_auto_20190305_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date_start'], 'verbose_name': 'Activitat'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-date_start'], 'verbose_name': 'Formació', 'verbose_name_plural': 'Formacions'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='axis',
            field=models.CharField(blank=True, choices=[('B', 'Eix B'), ('C', 'Eix C'), ('D', 'Eix D')], help_text='Eix de la convocatòria on es justificarà.', max_length=1, null=True, verbose_name='Eix'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organizer',
            field=models.CharField(choices=[('AT', 'Ateneu'), ('CM', 'Cercle Migracions'), ('CI', 'Cercle Incubació'), ('CC', 'Cercle Consum')], max_length=2, verbose_name='Qui ho fa'),
        ),
    ]
