# Generated by Django 2.1.3 on 2019-04-15 18:50

import cc_courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0010_activity_scanned_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='photo1',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='fotografia 1'),
        ),
        migrations.AddField(
            model_name='activity',
            name='photo2',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='fotografia 2'),
        ),
    ]
