# Generated by Django 2.1.3 on 2019-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0011_auto_20190415_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='justification',
            field=models.CharField(blank=True, choices=[('A', 'Ateneus Cooperatius'), ('J', 'Ajuntament'), ('2', 'Les 2 - cofinançat')], default='A', max_length=1, null=True, verbose_name='justificació'),
        ),
    ]
