# Generated by Django 2.1.3 on 2019-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0013_auto_20190415_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('F', 'Accions educatives'), ('A', 'Altres accions')], default='F', help_text='Determina el tipus de justificació', max_length=1, verbose_name="tipus d'acció"),
        ),
    ]
