# Generated by Django 2.1.3 on 2019-05-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0016_auto_20190502_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'entitat', 'verbose_name_plural': 'entitats'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity', verbose_name='entitat'),
        ),
    ]
