# Generated by Django 2.1.3 on 2019-05-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0017_auto_20190502_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Organizer', verbose_name='organitzadora'),
        ),
    ]
