# Generated by Django 2.1.3 on 2019-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0018_auto_20190506_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.AddField(
            model_name='course',
            name='for_minors',
            field=models.BooleanField(default=False, help_text='Determina el tipus de justificació', verbose_name='acció dirigida a menors'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='axis',
            field=models.CharField(blank=True, choices=[('A', 'Eix A'), ('B', 'Eix B'), ('C', 'Eix C'), ('D', 'Eix D'), ('E', 'Eix E'), ('F', 'Eix F')], help_text='Eix de la convocatòria on es justificarà.', max_length=1, null=True, verbose_name='eix'),
        ),
    ]
