# Generated by Django 2.0 on 2019-11-18 16:42

import cc_courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0026_auto_20191105_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='photo1',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='fotografia'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo2',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='document acreditatiu'),
        ),
    ]
