# Generated by Django 2.2.7 on 2020-01-20 18:43

import apps.coopolis.storage_backends
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0030_auto_20200120_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='scanned_signatures',
        ),
        migrations.AlterField(
            model_name='activity',
            name='file1',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='material de difusió'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo1',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='fotografia'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo2',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='document acreditatiu'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo3',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='fotografia 2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
