# Generated by Django 2.2.7 on 2020-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0032_auto_20200407_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityenrolled',
            options={'verbose_name': 'inscripció', 'verbose_name_plural': 'inscripcions'},
        ),
        migrations.AddField(
            model_name='activityenrolled',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="data d'inscripció"),
        ),
        migrations.AddField(
            model_name='activityenrolled',
            name='user_comments',
            field=models.TextField(blank=True, null=True, verbose_name='comentaris'),
        ),
    ]
