# Generated by Django 2.2.7 on 2020-06-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0035_auto_20200506_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cofunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'cofinançadora',
                'verbose_name_plural': 'cofinançadores',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='cofunded_ateneu',
            field=models.BooleanField(default=False, verbose_name='Cofinançat amb Ateneus Cooperatius'),
        ),
        migrations.AddField(
            model_name='activity',
            name='cofunded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cofunded_activities', to='cc_courses.Cofunding'),
        ),
    ]
