# Generated by Django 2.2.7 on 2020-06-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0036_auto_20200612_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'línia estratègica',
                'verbose_name_plural': 'línies estratègiques',
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='cofunded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cofunded_activities', to='cc_courses.Cofunding', verbose_name='Cofinançat'),
        ),
        migrations.AddField(
            model_name='activity',
            name='strategic_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_line_activities', to='cc_courses.StrategicLine', verbose_name='línia estratègica'),
        ),
    ]
