# Generated by Django 2.2.7 on 2020-06-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0037_auto_20200612_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='justification',
        ),
    ]
