# Generated by Django 2.2.7 on 2020-07-10 10:56

import apps.coopolis.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0039_activity_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='instruccions per participar'),
        ),
        migrations.AddField(
            model_name='activity',
            name='videocall_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='enllaç a la videotrucada'),
        ),
        migrations.CreateModel(
            name='ActivityResourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='fitxer')),
                ('name', models.CharField(max_length=120, verbose_name='nom del recurs')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='cc_courses.Activity')),
            ],
            options={
                'verbose_name': 'recurs',
                'verbose_name_plural': 'recursos',
                'ordering': ['name'],
            },
        ),
    ]
