# Generated by Django 2.2.7 on 2020-08-07 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0044_activityenrolled_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='instructions',
            field=models.TextField(blank=True, help_text='Aquest text s\'inclourà al correu de recordatori. És molt important que el formateig del text sigui el menor possible, i en particular, que si copieu i enganxeu el text d\'algun altre lloc cap aquí, ho feu amb l\'opció "enganxar sense format", ja que sinó arrossegarà molta informació de formateig que probablement farà que el correu es vegi malament.', null=True, verbose_name='instruccions per participar'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text="Persona de l'equip al càrrec de la sessió. Per aparèixer al desplegable, cal que la persona tingui activada l'opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_responsible', to=settings.AUTH_USER_MODEL, verbose_name='persona responsable'),
        ),
        migrations.AlterField(
            model_name='activityenrolled',
            name='waiting_list',
            field=models.BooleanField(default=False, verbose_name="en llista d'espera"),
        ),
    ]
