# Generated by Django 2.2.7 on 2021-03-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0046_auto_20210111_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='spots',
            field=models.IntegerField(default=0, help_text="Si hi ha inscripcions en llista d'espera i augmentes el número de places, passaran a confirmades i se'ls hi notificarà el canvi. Si redueixes el número de places per sota del total d'inscrites les que ja estaven confirmades seguiran confirmades. Aquestes autotatitzacions únicament s'activen si la sessió té una data futura.", verbose_name='places totals'),
        ),
    ]
