# Generated by Django 2.2.7 on 2021-05-05 14:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0049_auto_20210505_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
