# Generated by Django 2.1.3 on 2019-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataExports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('subsidy_period', models.CharField(blank=True, choices=[('2017', '2016-2017'), ('2018', '2017-2018'), ('2019', '2018-2019')], default=2019, max_length=4, null=True, verbose_name='convocatòria')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='apunts')),
                ('function_name', models.CharField(help_text='No modifiqueu aquesta dada.', max_length=150, unique=True, verbose_name='nom de la funció')),
            ],
            options={
                'verbose_name': 'exportació',
                'verbose_name_plural': 'exportacions',
                'ordering': ['-subsidy_period'],
            },
        ),
    ]
