# Generated by Django 2.1.3 on 2019-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0003_auto_20190620_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexports',
            name='ignore_errors',
            field=models.BooleanField(default=False, help_text="Si s'activa, es podràn generar els excels de justificació encara que hi hagi errors a les dades. Els excels que es generin així NO es podran volcar a l'excel real!", verbose_name='Ignorar errors'),
        ),
    ]
