# Generated by Django 2.1.3 on 2019-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0004_dataexports_ignore_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexportscorrelation',
            name='correlated_data',
            field=models.CharField(blank=True, help_text="Com ha de quedar el valor quan l'exportem per la justificació.", max_length=200, null=True, verbose_name='dada correlacionada'),
        ),
    ]
