# Generated by Django 2.2.7 on 2020-01-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0007_auto_20191031_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
                ('date_start', models.DateField(verbose_name="dia d'inici")),
                ('date_end', models.DateField(verbose_name='dia de finalització')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name="número d'expedient")),
            ],
            options={
                'verbose_name': 'convocatòria',
                'verbose_name_plural': 'convocatòries',
            },
        ),
    ]
