# Generated by Django 2.2.7 on 2020-01-17 11:08

from django.db import migrations
import datetime


def populate_subsidy_data(apps, schema_editor):
    SubsidyPeriod = apps.get_model('dataexports', 'SubsidyPeriod')

    exist = SubsidyPeriod.objects.filter(name='2016-2017')
    if exist.count() == 0:
        obj = SubsidyPeriod(
            name='2016-2017',
            date_start=datetime.datetime(2016, 11, 1),
            date_end=datetime.datetime(2017, 10, 31),
        )
        obj.save()

    exist = SubsidyPeriod.objects.filter(name='2017-2018')
    if exist.count() == 0:
        obj = SubsidyPeriod(
            name='2017-2018',
            date_start=datetime.datetime(2017, 11, 1),
            date_end=datetime.datetime(2018, 10, 31),
        )
        obj.save()

    exist = SubsidyPeriod.objects.filter(name='2018-2019')
    if exist.count() == 0:
        obj = SubsidyPeriod(
            name='2018-2019',
            date_start=datetime.datetime(2018, 11, 1),
            date_end=datetime.datetime(2019, 10, 31),
        )
        obj.save()

    exist = SubsidyPeriod.objects.filter(name='2019-2020')
    if exist.count() == 0:
        obj = SubsidyPeriod(
            name='2019-2020',
            date_start=datetime.datetime(2019, 11, 1),
            date_end=datetime.datetime(2020, 10, 31),
        )
        obj.save()


def link_export_subsidy_number(apps, schema_editor):
    Export = apps.get_model('dataexports', 'DataExports')
    SubsidyPeriod = apps.get_model('dataexports', 'SubsidyPeriod')
    for export in Export.objects.all():
        starting_year = int(export.subsidy_period) - 1
        subsidyperiod = SubsidyPeriod.objects.get(name__startswith=starting_year)
        export.subsidy_period_link = subsidyperiod
        export.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0009_dataexports_subsidy_period_link'),
    ]

    operations = [
        migrations.RunPython(populate_subsidy_data),
        migrations.RunPython(link_export_subsidy_number),
    ]
