# Generated by Django 2.2.7 on 2020-01-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0010_transfer_subsidy_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataexports',
            name='subsidy_period',
        ),
        migrations.RenameField(
            model_name='dataexports',
            old_name='subsidy_period_link',
            new_name='subsidy_period',
        ),
    ]
