# Generated by Django 2.2.7 on 2021-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0017_auto_20210111_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexports',
            name='function_name',
            field=models.CharField(help_text='No modifiqueu aquesta dada.', max_length=150, verbose_name='nom de la funció'),
        ),
    ]
