# Generated by Django 3.2.9 on 2021-11-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0018_auto_20210512_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexports',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subsidyperiod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='dataexports',
            unique_together={('name', 'subsidy_period')},
        ),
    ]
