"""
Aquest llistat ha estat exportat de l'excel de justificació de la
convocatòria 2018-2019.
"""


def migration_id_equivalences():
    return (
        {
            "name" : "Igualada",
            "town_id" : 359,
            "new_id": 358
        },
        {
            "name" : "Molins de Rei",
            "town_id" : 441,
            "new_id": 439
        },
        {
            "name" : "Montcada i Reixac",
            "town_id" : 452,
            "new_id": 450
        },
        {
            "name" : "Montgat",
            "town_id" : 459,
            "new_id": 457
        },
        {
            "name" : "Pallejà",
            "town_id" : 522,
            "new_id": 520
        },
        {
            "name" : "Sant Adrià de Besòs",
            "town_id" : 653,
            "new_id": 651
        },
        {
            "name" : "Sant Andreu de la Barca",
            "town_id" : 655,
            "new_id": 653
        },
        {
            "name" : "Sant Boi de Llobregat",
            "town_id" : 661,
            "new_id": 659
        },
        {
            "name" : "Sant Cugat del Vallès",
            "town_id" : 668,
            "new_id": 666
        },
        {
            "name" : "Sant Feliu de Llobregat",
            "town_id" : 676,
            "new_id": 674
        },
        {
            "name" : "Sant Just Desvern",
            "town_id" : 702,
            "new_id": 700
        },
        {
            "name" : "Santa Coloma de Gramenet",
            "town_id" : 743,
            "new_id": 741
        },
        {
            "name" : "Viladecans",
            "town_id" : 899,
            "new_id": 897
        },
        {
            "name" : "el Prat de Llobregat",
            "town_id" : 581,
            "new_id": 579
        },
        {
            "name" : "l'Hospitalet de Llobregat",
            "town_id" : 356,
            "new_id": 355
        },
        {
            "name" : "la Palma de Cervelló",
            "town_id" : 523,
            "new_id": 521
        }
    )

def towns():
    return [
        ("ABELLA DE LA CONCA"),
        ("ABRERA"),
        ("AGER"),
        ("AGRAMUNT"),
        ("AGUILAR DE SEGARRA"),
        ("AGULLANA"),
        ("AIGUAFREDA"),
        ("AIGUAMURCIA"),
        ("AIGUAVIVA"),
        ("AITONA"),
        ("ALAMUS, ELS"),
        ("ALAS I CERC"),
        ("ALBAGES, L'"),
        ("ALBANYA"),
        ("ALBATARREC"),
        ("ALBESA"),
        ("ALBI, L'"),
        ("ALBINYANA"),
        ("ALBIOL, L'"),
        ("ALBONS"),
        ("ALCANAR"),
        ("ALCANO"),
        ("ALCARRAS"),
        ("ALCOLETGE"),
        ("ALCOVER"),
        ("ALDEA, L'"),
        ("ALDOVER"),
        ("ALEIXAR, L'"),
        ("ALELLA"),
        ("ALFARA DE CARLES"),
        ("ALFARRAS"),
        ("ALFES"),
        ("ALFORJA"),
        ("ALGERRI"),
        ("ALGUAIRE"),
        ("ALINS"),
        ("ALIO"),
        ("ALMACELLES"),
        ("ALMATRET"),
        ("ALMENAR"),
        ("ALMOSTER"),
        ("ALOS DE BALAGUER"),
        ("ALP"),
        ("ALPENS"),
        ("ALPICAT"),
        ("ALT ANEU"),
        ("ALTAFULLA"),
        ("AMER"),
        ("AMETLLA DE MAR, L'"),
        ("AMETLLA DEL VALLES, L'"),
        ("AMPOLLA, L'"),
        ("AMPOSTA"),
        ("ANGLES"),
        ("ANGLESOLA"),
        ("ARBECA"),
        ("ARBOÇ, L'"),
        ("ARBOLI"),
        ("ARBUCIES"),
        ("ARENYS DE MAR"),
        ("ARENYS DE MUNT"),
        ("ARGELAGUER"),
        ("ARGENÇOLA"),
        ("ARGENTERA, L'"),
        ("ARGENTONA"),
        ("ARMENTERA, L'"),
        ("ARNES"),
        ("ARRES"),
        ("ARSEGUEL"),
        ("ARTES"),
        ("ARTESA DE LLEIDA"),
        ("ARTESA DE SEGRE"),
        ("ASCO"),
        ("ASPA"),
        ("AVELLANES I SANTA LINYA, LES"),
        ("AVIA"),
        ("AVINYO"),
        ("AVINYONET DE PUIGVENTOS"),
        ("AVINYONET DEL PENEDES"),
        ("BADALONA"),
        ("BADIA DEL VALLES"),
        ("BAGA"),
        ("BAIX PALLARS"),
        ("BALAGUER"),
        ("BALENYA"),
        ("BALSARENY"),
        ("BANYERES DEL PENEDES"),
        ("BANYOLES"),
        ("BARBENS"),
        ("BARBERA DE LA CONCA"),
        ("BARBERA DEL VALLES"),
        ("BARCELONA"),
        ("BARONIA DE RIALB, LA"),
        ("BASCARA"),
        ("BASSELLA"),
        ("BATEA"),
        ("BAUSEN"),
        ("BEGUES"),
        ("BEGUR"),
        ("BELIANES"),
        ("BELLAGUARDA"),
        ("BELLCAIRE D'EMPORDA"),
        ("BELLCAIRE D'URGELL"),
        ("BELL-LLOC D'URGELL"),
        ("BELLMUNT DEL PRIORAT"),
        ("BELLMUNT D'URGELL"),
        ("BELLPRAT"),
        ("BELLPUIG"),
        ("BELLVEI"),
        ("BELLVER DE CERDANYA"),
        ("BELLVIS"),
        ("BENAVENT DE SEGRIA"),
        ("BENIFALLET"),
        ("BENISSANET"),
        ("BERGA"),
        ("BESALU"),
        ("BESCANO"),
        ("BEUDA"),
        ("BIGUES I RIELLS"),
        ("BIOSCA"),
        ("BISBAL DE FALSET, LA"),
        ("BISBAL DEL PENEDES, LA"),
        ("BISBAL D'EMPORDA, LA"),
        ("BIURE"),
        ("BLANCAFORT"),
        ("BLANES"),
        ("BOADELLA I LES ESCAULES"),
        ("BOLVIR"),
        ("BONASTRE"),
        ("BORDES, ES"),
        ("BORDILS"),
        ("BORGES BLANQUES, LES"),
        ("BORGES DEL CAMP, LES"),
        ("BORRASSA"),
        ("BORREDA"),
        ("BOSSOST"),
        ("BOT"),
        ("BOTARELL"),
        ("BOVERA"),
        ("BRAFIM"),
        ("BREDA"),
        ("BRUC, EL"),
        ("BRULL, EL"),
        ("BRUNYOLA"),
        ("CABACES"),
        ("CABANABONA"),
        ("CABANELLES"),
        ("CABANES"),
        ("CABANYES, LES"),
        ("CABO"),
        ("CABRA DEL CAMP"),
        ("CABRERA D'ANOIA"),
        ("CABRERA DE MAR"),
        ("CABRILS"),
        ("CADAQUES"),
        ("CALAF"),
        ("CALAFELL"),
        ("CALDERS"),
        ("CALDES DE MALAVELLA"),
        ("CALDES DE MONTBUI"),
        ("CALDES D'ESTRAC"),
        ("CALELLA"),
        ("CALLDETENES"),
        ("CALLUS"),
        ("CALONGE"),
        ("CALONGE DE SEGARRA"),
        ("CAMARASA"),
        ("CAMARLES"),
        ("CAMBRILS"),
        ("CAMOS"),
        ("CAMPDEVANOL"),
        ("CAMPELLES"),
        ("CAMPINS"),
        ("CAMPLLONG"),
        ("CAMPRODON"),
        ("CANEJAN"),
        ("CANET D'ADRI"),
        ("CANET DE MAR"),
        ("CANONJA, LA"),
        ("CANOVELLES"),
        ("CANOVES I SAMALUS"),
        ("CANTALLOPS"),
        ("CANYELLES"),
        ("CAPAFONTS"),
        ("CAPÇANES"),
        ("CAPELLADES"),
        ("CAPMANY"),
        ("CAPOLAT"),
        ("CARDEDEU"),
        ("CARDONA"),
        ("CARME"),
        ("CASERES"),
        ("CASSA DE LA SELVA"),
        ("CASSERRES"),
        ("CASTELL DE L'ARENY"),
        ("CASTELL DE MUR"),
        ("CASTELLAR DE LA RIBERA"),
        ("CASTELLAR DE N'HUG"),
        ("CASTELLAR DEL RIU"),
        ("CASTELLAR DEL VALLES"),
        ("CASTELLBELL I EL VILAR"),
        ("CASTELLBISBAL"),
        ("CASTELLCIR"),
        ("CASTELLDANS"),
        ("CASTELLDEFELS"),
        ("CASTELLET I LA GORNAL"),
        ("CASTELLFOLLIT DE LA ROCA"),
        ("CASTELLFOLLIT DE RIUBREGOS"),
        ("CASTELLFOLLIT DEL BOIX"),
        ("CASTELLGALI"),
        ("CASTELLNOU DE BAGES"),
        ("CASTELLNOU DE SEANA"),
        ("CASTELLO DE FARFANYA"),
        ("CASTELLO D'EMPURIES"),
        ("CASTELLOLI"),
        ("CASTELL-PLATJA D'ARO"),
        ("CASTELLSERA"),
        ("CASTELLTERÇOL"),
        ("CASTELLVELL DEL CAMP"),
        ("CASTELLVI DE LA MARCA"),
        ("CASTELLVI DE ROSANES"),
        ("CATLLAR, EL"),
        ("CAVA"),
        ("CELLERA DE TER, LA"),
        ("CELRA"),
        ("CENTELLES"),
        ("CERCS"),
        ("CERDANYOLA DEL VALLES"),
        ("CERVELLO"),
        ("CERVERA"),
        ("CERVIA DE LES GARRIGUES"),
        ("CERVIA DE TER"),
        ("CISTELLA"),
        ("CIUTADILLA"),
        ("CLARIANA DE CARDENER"),
        ("COGUL, EL"),
        ("COLERA"),
        ("COLL DE NARGO"),
        ("COLLBATO"),
        ("COLLDEJOU"),
        ("COLLSUSPINA"),
        ("COLOMERS"),
        ("COMA I LA PEDRA, LA"),
        ("CONCA DE DALT"),
        ("CONESA"),
        ("CONSTANTI"),
        ("COPONS"),
        ("CORBERA DE LLOBREGAT"),
        ("CORBERA D'EBRE"),
        ("CORBINS"),
        ("CORÇA"),
        ("CORNELLA DE LLOBREGAT"),
        ("CORNELLA DEL TERRI"),
        ("CORNUDELLA DE MONTSANT"),
        ("CREIXELL"),
        ("CRESPIA"),
        ("CRUILLES, MONELLS I SANT SADURNI DE L'HEURA"),
        ("CUBELLES"),
        ("CUBELLS"),
        ("CUNIT"),
        ("DARNIUS"),
        ("DAS"),
        ("DELTEBRE"),
        ("DOSRIUS"),
        ("DUESAIGUES"),
        ("ESCALA, L'"),
        ("ESPARREGUERA"),
        ("ESPINELVES"),
        ("ESPLUGA CALBA, L'"),
        ("ESPLUGA DE FRANCOLI, L'"),
        ("ESPLUGUES DE LLOBREGAT"),
        ("ESPOLLA"),
        ("ESPONELLA"),
        ("ESPOT"),
        ("ESPUNYOLA, L'"),
        ("ESTAMARIU"),
        ("ESTANY, L'"),
        ("ESTARAS"),
        ("ESTERRI D'ANEU"),
        ("ESTERRI DE CARDOS"),
        ("FALSET"),
        ("FAR D'EMPORDA, EL"),
        ("FARRERA"),
        ("FATARELLA, LA"),
        ("FEBRO, LA"),
        ("FIGARO-MONTMANY"),
        ("FIGOLS"),
        ("FIGOLS I ALINYA"),
        ("FIGUERA, LA"),
        ("FIGUERES"),
        ("FIGUEROLA DEL CAMP"),
        ("FLAÇA"),
        ("FLIX"),
        ("FLORESTA, LA"),
        ("FOGARS DE LA SELVA"),
        ("FOGARS DE MONTCLUS"),
        ("FOIXA"),
        ("FOLGUEROLES"),
        ("FONDARELLA"),
        ("FONOLLOSA"),
        ("FONTANALS DE CERDANYA"),
        ("FONTANILLES"),
        ("FONTCOBERTA"),
        ("FONT-RUBI"),
        ("FORADADA"),
        ("FORALLAC"),
        ("FORES"),
        ("FORNELLS DE LA SELVA"),
        ("FORTIA"),
        ("FRANQUESES DEL VALLES, LES"),
        ("FREGINALS"),
        ("FULIOLA, LA"),
        ("FULLEDA"),
        ("GAIA"),
        ("GALERA, LA"),
        ("GALLIFA"),
        ("GANDESA"),
        ("GARCIA"),
        ("GARIDELLS, ELS"),
        ("GARRIGA, LA"),
        ("GARRIGAS"),
        ("GARRIGOLES"),
        ("GARRIGUELLA"),
        ("GAVA"),
        ("GAVET DE LA CONCA"),
        ("GELIDA"),
        ("GER"),
        ("GIMENELLS I EL PLA DE LA FONT"),
        ("GINESTAR"),
        ("GIRONA"),
        ("GIRONELLA"),
        ("GISCLARENY"),
        ("GODALL"),
        ("GOLMES"),
        ("GOMBREN"),
        ("GOSOL"),
        ("GRANADA, LA"),
        ("GRANADELLA, LA"),
        ("GRANERA"),
        ("GRANJA D'ESCARP, LA"),
        ("GRANOLLERS"),
        ("GRANYANELLA"),
        ("GRANYENA DE LES GARRIGUES"),
        ("GRANYENA DE SEGARRA"),
        ("GRATALLOPS"),
        ("GUALBA"),
        ("GUALTA"),
        ("GUARDIOLA DE BERGUEDA"),
        ("GUIAMETS, ELS"),
        ("GUILS DE CERDANYA"),
        ("GUIMERA"),
        ("GUINGUETA D'ANEU, LA"),
        ("GUISSONA"),
        ("GUIXERS"),
        ("GURB"),
        ("HORTA DE SANT JOAN"),
        ("HOSPITALET DE LLOBREGAT, L'"),
        ("HOSTALETS DE PIEROLA, ELS"),
        ("HOSTALRIC"),
        ("IGUALADA"),
        ("ISONA I CONCA DELLA"),
        ("ISOVOL"),
        ("IVARS DE NOGUERA"),
        ("IVARS D'URGELL"),
        ("IVORRA"),
        ("JAFRE"),
        ("JONQUERA, LA"),
        ("JORBA"),
        ("JOSA I TUIXEN"),
        ("JUIA"),
        ("JUNCOSA"),
        ("JUNEDA"),
        ("LES"),
        ("LINYOLA"),
        ("LLACUNA, LA"),
        ("LLADO"),
        ("LLADORRE"),
        ("LLADURS"),
        ("LLAGOSTA, LA"),
        ("LLAGOSTERA"),
        ("LLAMBILLES"),
        ("LLANARS"),
        ("LLANÇA"),
        ("LLARDECANS"),
        ("LLAVORSI"),
        ("LLEIDA"),
        ("LLERS"),
        ("LLES DE CERDANYA"),
        ("LLIÇA D'AMUNT"),
        ("LLIÇA DE VALL"),
        ("LLIMIANA"),
        ("LLINARS DEL VALLES"),
        ("LLIVIA"),
        ("LLOAR, EL"),
        ("LLOBERA"),
        ("LLORAC"),
        ("LLORENÇ DEL PENEDES"),
        ("LLORET DE MAR"),
        ("LLOSSES, LES"),
        ("LLUÇA"),
        ("MAÇANET DE CABRENYS"),
        ("MAÇANET DE LA SELVA"),
        ("MADREMANYA"),
        ("MAIA DE MONTCAL"),
        ("MAIALS"),
        ("MALDA"),
        ("MALGRAT DE MAR"),
        ("MALLA"),
        ("MANLLEU"),
        ("MANRESA"),
        ("MARÇA"),
        ("MARGALEF"),
        ("MARGANELL"),
        ("MARTORELL"),
        ("MARTORELLES"),
        ("MAS DE BARBERANS"),
        ("MASARAC"),
        ("MASDENVERGE"),
        ("MASIES DE RODA, LES"),
        ("MASIES DE VOLTREGA, LES"),
        ("MASLLORENÇ"),
        ("MASNOU, EL"),
        ("MASO, LA"),
        ("MASPUJOLS"),
        ("MASQUEFA"),
        ("MASROIG, EL"),
        ("MASSALCOREIG"),
        ("MASSANES"),
        ("MASSOTERES"),
        ("MATADEPERA"),
        ("MATARO"),
        ("MEDIONA"),
        ("MENARGUENS"),
        ("MERANGES"),
        ("MIERES"),
        ("MILA, EL"),
        ("MIRALCAMP"),
        ("MIRAVET"),
        ("MOIA"),
        ("MOLAR, EL"),
        ("MOLINS DE REI"),
        ("MOLLERUSSA"),
        ("MOLLET DE PERALADA"),
        ("MOLLET DEL VALLES"),
        ("MOLLO"),
        ("MOLSOSA, LA"),
        ("MONISTROL DE CALDERS"),
        ("MONISTROL DE MONTSERRAT"),
        ("MONTAGUT I OIX"),
        ("MONTBLANC"),
        ("MONTBRIO DEL CAMP"),
        ("MONTCADA I REIXAC"),
        ("MONTCLAR"),
        ("MONTELLA I MARTINET"),
        ("MONTESQUIU"),
        ("MONTFERRER I CASTELLBO"),
        ("MONTFERRI"),
        ("MONTGAI"),
        ("MONTGAT"),
        ("MONTMAJOR"),
        ("MONTMANEU"),
        ("MONTMELL, EL"),
        ("MONTMELO"),
        ("MONTOLIU DE LLEIDA"),
        ("MONTOLIU DE SEGARRA"),
        ("MONTORNES DE SEGARRA"),
        ("MONTORNES DEL VALLES"),
        ("MONT-RAL"),
        ("MONT-RAS"),
        ("MONT-ROIG DEL CAMP"),
        ("MONTSENY"),
        ("MORA D'EBRE"),
        ("MORA LA NOVA"),
        ("MORELL, EL"),
        ("MORERA DE MONTSANT, LA"),
        ("MUNTANYOLA"),
        ("MURA"),
        ("NALEC"),
        ("NAUT ARAN"),
        ("NAVARCLES"),
        ("NAVAS"),
        ("NAVATA"),
        ("NAVES"),
        ("NOU DE BERGUEDA, LA"),
        ("NOU DE GAIA, LA"),
        ("NULLES"),
        ("ODEN"),
        ("ODENA"),
        ("OGASSA"),
        ("OLERDOLA"),
        ("OLESA DE BONESVALLS"),
        ("OLESA DE MONTSERRAT"),
        ("OLIANA"),
        ("OLIOLA"),
        ("OLIUS"),
        ("OLIVELLA"),
        ("OLOST"),
        ("OLOT"),
        ("OLUGES, LES"),
        ("OLVAN"),
        ("OMELLONS, ELS"),
        ("OMELLS DE NA GAIA, ELS"),
        ("ORDIS"),
        ("ORGANYA"),
        ("ORIS"),
        ("ORISTA"),
        ("ORPI"),
        ("ORRIUS"),
        ("OS DE BALAGUER"),
        ("OSOR"),
        ("OSSO DE SIO"),
        ("PACS DEL PENEDES"),
        ("PALAFOLLS"),
        ("PALAFRUGELL"),
        ("PALAMOS"),
        ("PALAU D'ANGLESOLA, EL"),
        ("PALAU DE SANTA EULALIA"),
        ("PALAU-SATOR"),
        ("PALAU-SAVERDERA"),
        ("PALAU-SOLITA I PLEGAMANS"),
        ("PALLARESOS, ELS"),
        ("PALLEJA"),
        ("PALMA DE CERVELLO, LA"),
        ("PALMA D'EBRE, LA"),
        ("PALOL DE REVARDIT"),
        ("PALS"),
        ("PAPIOL, EL"),
        ("PARDINES"),
        ("PARETS DEL VALLES"),
        ("PARLAVA"),
        ("PASSANANT I BELLTALL"),
        ("PAU"),
        ("PAULS"),
        ("PEDRET I MARZA"),
        ("PENELLES"),
        ("PERA, LA"),
        ("PERAFITA"),
        ("PERAFORT"),
        ("PERALADA"),
        ("PERAMOLA"),
        ("PERELLO, EL"),
        ("PIERA"),
        ("PILES, LES"),
        ("PINEDA DE MAR"),
        ("PINELL DE BRAI, EL"),
        ("PINELL DE SOLSONES"),
        ("PINOS"),
        ("PIRA"),
        ("PLA DE SANTA MARIA, EL"),
        ("PLA DEL PENEDES, EL"),
        ("PLANES D'HOSTOLES, LES"),
        ("PLANOLES"),
        ("PLANS DE SIO, ELS"),
        ("POAL, EL"),
        ("POBLA DE CERVOLES, LA"),
        ("POBLA DE CLARAMUNT, LA"),
        ("POBLA DE LILLET, LA"),
        ("POBLA DE MAFUMET, LA"),
        ("POBLA DE MASSALUCA, LA"),
        ("POBLA DE MONTORNES, LA"),
        ("POBLA DE SEGUR, LA"),
        ("POBOLEDA"),
        ("POLINYA"),
        ("PONT D'ARMENTERA, EL"),
        ("PONT DE BAR, EL"),
        ("PONT DE MOLINS"),
        ("PONT DE SUERT, EL"),
        ("PONT DE VILOMARA I ROCAFORT, EL"),
        ("PONTILS"),
        ("PONTONS"),
        ("PONTOS"),
        ("PONTS"),
        ("PORQUERES"),
        ("PORRERA"),
        ("PORT DE LA SELVA, EL"),
        ("PORTBOU"),
        ("PORTELLA, LA"),
        ("PRADELL DE LA TEIXETA"),
        ("PRADES"),
        ("PRAT DE COMTE"),
        ("PRAT DE LLOBREGAT, EL"),
        ("PRATDIP"),
        ("PRATS DE LLUÇANES"),
        ("PRATS DE REI, ELS"),
        ("PRATS I SANSOR"),
        ("PREIXANA"),
        ("PREIXENS"),
        ("PREMIA DE DALT"),
        ("PREMIA DE MAR"),
        ("PRESES, LES"),
        ("PRULLANS"),
        ("PUIGCERDA"),
        ("PUIGDALBER"),
        ("PUIGGROS"),
        ("PUIGPELAT"),
        ("PUIG-REIG"),
        ("PUIGVERD D'AGRAMUNT"),
        ("PUIGVERD DE LLEIDA"),
        ("PUJALT"),
        ("QUAR, LA"),
        ("QUART"),
        ("QUERALBS"),
        ("QUEROL"),
        ("RABOS"),
        ("RAJADELL"),
        ("RASQUERA"),
        ("REGENCOS"),
        ("RELLINARS"),
        ("RENAU"),
        ("REUS"),
        ("RIALP"),
        ("RIBA, LA"),
        ("RIBA-ROJA D'EBRE"),
        ("RIBERA D'ONDARA"),
        ("RIBERA D'URGELLET"),
        ("RIBES DE FRESER"),
        ("RIELLS I VIABREA"),
        ("RIERA DE GAIA, LA"),
        ("RINER"),
        ("RIPOLL"),
        ("RIPOLLET"),
        ("RIU DE CERDANYA"),
        ("RIUDARENES"),
        ("RIUDAURA"),
        ("RIUDECANYES"),
        ("RIUDECOLS"),
        ("RIUDELLOTS DE LA SELVA"),
        ("RIUDOMS"),
        ("RIUMORS"),
        ("ROCA DEL VALLES, LA"),
        ("ROCAFORT DE QUERALT"),
        ("RODA DE BARA"),
        ("RODA DE TER"),
        ("RODONYA"),
        ("ROQUETES"),
        ("ROSES"),
        ("ROSSELLO"),
        ("ROURELL, EL"),
        ("RUBI"),
        ("RUBIO"),
        ("RUPIA"),
        ("RUPIT I PRUIT"),
        ("SABADELL"),
        ("SAGAS"),
        ("SALAS DE PALLARS"),
        ("SALDES"),
        ("SALES DE LLIERCA"),
        ("SALLENT"),
        ("SALOMO"),
        ("SALOU"),
        ("SALT"),
        ("SANAUJA"),
        ("SANT ADRIA DE BESOS"),
        ("SANT AGUSTI DE LLUÇANES"),
        ("SANT ANDREU DE LA BARCA"),
        ("SANT ANDREU DE LLAVANERES"),
        ("SANT ANDREU SALOU"),
        ("SANT ANIOL DE FINESTRES"),
        ("SANT ANTONI DE VILAMAJOR"),
        ("SANT BARTOMEU DEL GRAU"),
        ("SANT BOI DE LLOBREGAT"),
        ("SANT BOI DE LLUÇANES"),
        ("SANT CARLES DE LA RAPITA"),
        ("SANT CEBRIA DE VALLALTA"),
        ("SANT CELONI"),
        ("SANT CLIMENT DE LLOBREGAT"),
        ("SANT CLIMENT SESCEBES"),
        ("SANT CUGAT DEL VALLES"),
        ("SANT CUGAT SESGARRIGUES"),
        ("SANT ESTEVE DE LA SARGA"),
        ("SANT ESTEVE DE PALAUTORDERA"),
        ("SANT ESTEVE SESROVIRES"),
        ("SANT FELIU DE BUIXALLEU"),
        ("SANT FELIU DE CODINES"),
        ("SANT FELIU DE GUIXOLS"),
        ("SANT FELIU DE LLOBREGAT"),
        ("SANT FELIU DE PALLEROLS"),
        ("SANT FELIU SASSERRA"),
        ("SANT FERRIOL"),
        ("SANT FOST DE CAMPSENTELLES"),
        ("SANT FRUITOS DE BAGES"),
        ("SANT GREGORI"),
        ("SANT GUIM DE FREIXENET"),
        ("SANT GUIM DE LA PLANA"),
        ("SANT HILARI SACALM"),
        ("SANT HIPOLIT DE VOLTREGA"),
        ("SANT ISCLE DE VALLALTA"),
        ("SANT JAUME DE FRONTANYA"),
        ("SANT JAUME DE LLIERCA"),
        ("SANT JAUME DELS DOMENYS"),
        ("SANT JAUME D'ENVEJA"),
        ("SANT JOAN DE LES ABADESSES"),
        ("SANT JOAN DE MOLLET"),
        ("SANT JOAN DE VILATORRADA"),
        ("SANT JOAN DESPI"),
        ("SANT JOAN LES FONTS"),
        ("SANT JORDI DESVALLS"),
        ("SANT JULIA DE CERDANYOLA"),
        ("SANT JULIA DE RAMIS"),
        ("SANT JULIA DE VILATORTA"),
        ("SANT JULIA DEL LLOR I BONMATI"),
        ("SANT JUST DESVERN"),
        ("SANT LLORENÇ DE LA MUGA"),
        ("SANT LLORENÇ DE MORUNYS"),
        ("SANT LLORENÇ D'HORTONS"),
        ("SANT LLORENÇ SAVALL"),
        ("SANT MARTI D'ALBARS"),
        ("SANT MARTI DE CENTELLES"),
        ("SANT MARTI DE LLEMENA"),
        ("SANT MARTI DE RIUCORB"),
        ("SANT MARTI DE TOUS"),
        ("SANT MARTI SARROCA"),
        ("SANT MARTI SESGUEIOLES"),
        ("SANT MARTI VELL"),
        ("SANT MATEU DE BAGES"),
        ("SANT MIQUEL DE CAMPMAJOR"),
        ("SANT MIQUEL DE FLUVIA"),
        ("SANT MORI"),
        ("SANT PAU DE SEGURIES"),
        ("SANT PERE DE RIBES"),
        ("SANT PERE DE RIUDEBITLLES"),
        ("SANT PERE DE TORELLO"),
        ("SANT PERE DE VILAMAJOR"),
        ("SANT PERE PESCADOR"),
        ("SANT PERE SALLAVINERA"),
        ("SANT POL DE MAR"),
        ("SANT QUINTI DE MEDIONA"),
        ("SANT QUIRZE DE BESORA"),
        ("SANT QUIRZE DEL VALLES"),
        ("SANT QUIRZE SAFAJA"),
        ("SANT RAMON"),
        ("SANT SADURNI D'ANOIA"),
        ("SANT SADURNI D'OSORMORT"),
        ("SANT SALVADOR DE GUARDIOLA"),
        ("SANT VICENÇ DE CASTELLET"),
        ("SANT VICENÇ DE MONTALT"),
        ("SANT VICENÇ DE TORELLO"),
        ("SANT VICENÇ DELS HORTS"),
        ("SANTA BARBARA"),
        ("SANTA CECILIA DE VOLTREGA"),
        ("SANTA COLOMA DE CERVELLO"),
        ("SANTA COLOMA DE FARNERS"),
        ("SANTA COLOMA DE GRAMENET"),
        ("SANTA COLOMA DE QUERALT"),
        ("SANTA CRISTINA D'ARO"),
        ("SANTA EUGENIA DE BERGA"),
        ("SANTA EULALIA DE RIUPRIMER"),
        ("SANTA EULALIA DE RONÇANA"),
        ("SANTA FE DEL PENEDES"),
        ("SANTA LLOGAIA D'ALGUEMA"),
        ("SANTA MARGARIDA DE MONTBUI"),
        ("SANTA MARGARIDA I ELS MONJOS"),
        ("SANTA MARIA DE BESORA"),
        ("SANTA MARIA DE CORCO"),
        ("SANTA MARIA DE MARTORELLES"),
        ("SANTA MARIA DE MERLES"),
        ("SANTA MARIA DE MIRALLES"),
        ("SANTA MARIA DE PALAUTORDERA"),
        ("SANTA MARIA D'OLO"),
        ("SANTA OLIVA"),
        ("SANTA PAU"),
        ("SANTA PERPETUA DE MOGODA"),
        ("SANTA SUSANNA"),
        ("SANTPEDOR"),
        ("SARRAL"),
        ("SARRIA DE TER"),
        ("SARROCA DE BELLERA"),
        ("SARROCA DE LLEIDA"),
        ("SAUS,CAMALLERA I LLAMPAIES"),
        ("SAVALLA DEL COMTAT"),
        ("SECUITA, LA"),
        ("SELVA DE MAR, LA"),
        ("SELVA DEL CAMP, LA"),
        ("SENAN"),
        ("SENIA, LA"),
        ("SENTERADA"),
        ("SENTIU DE SIO, LA"),
        ("SENTMENAT"),
        ("SERINYA"),
        ("SEROS"),
        ("SERRA DE DARO"),
        ("SETCASES"),
        ("SEU D'URGELL, LA"),
        ("SEVA"),
        ("SIDAMON"),
        ("SILS"),
        ("SITGES"),
        ("SIURANA"),
        ("SOBREMUNT"),
        ("SOLERAS, EL"),
        ("SOLIVELLA"),
        ("SOLSONA"),
        ("SORA"),
        ("SORIGUERA"),
        ("SORT"),
        ("SOSES"),
        ("SUBIRATS"),
        ("SUDANELL"),
        ("SUNYER"),
        ("SURIA"),
        ("SUSQUEDA"),
        ("TAGAMANENT"),
        ("TALAMANCA"),
        ("TALARN"),
        ("TALAVERA"),
        ("TALLADA D'EMPORDA, LA"),
        ("TARADELL"),
        ("TARRAGONA"),
        ("TARREGA"),
        ("TARRES"),
        ("TARROJA DE SEGARRA"),
        ("TAVERNOLES"),
        ("TAVERTET"),
        ("TEIA"),
        ("TERMENS"),
        ("TERRADES"),
        ("TERRASSA"),
        ("TIANA"),
        ("TIRVIA"),
        ("TIURANA"),
        ("TIVENYS"),
        ("TIVISSA"),
        ("TONA"),
        ("TORA"),
        ("TORDERA"),
        ("TORELLO"),
        ("TORMS, ELS"),
        ("TORNABOUS"),
        ("TORRE DE CABDELLA, LA"),
        ("TORRE DE CLARAMUNT, LA"),
        ("TORRE DE FONTAUBELLA, LA"),
        ("TORRE DE L'ESPANYOL, LA"),
        ("TORREBESSES"),
        ("TORREDEMBARRA"),
        ("TORREFARRERA"),
        ("TORREFETA I FLOREJACS"),
        ("TORREGROSSA"),
        ("TORRELAMEU"),
        ("TORRELAVIT"),
        ("TORRELLES DE FOIX"),
        ("TORRELLES DE LLOBREGAT"),
        ("TORRENT"),
        ("TORRES DE SEGRE"),
        ("TORRE-SERONA"),
        ("TORROELLA DE FLUVIA"),
        ("TORROELLA DE MONTGRI"),
        ("TORROJA DEL PRIORAT"),
        ("TORTELLA"),
        ("TORTOSA"),
        ("TOSES"),
        ("TOSSA DE MAR"),
        ("TREMP"),
        ("ULLA"),
        ("ULLASTRELL"),
        ("ULLASTRET"),
        ("ULLDECONA"),
        ("ULLDEMOLINS"),
        ("ULTRAMORT"),
        ("URUS"),
        ("VACARISSES"),
        ("VAJOL, LA"),
        ("VALL DE BIANYA, LA"),
        ("VALL DE BOI, LA"),
        ("VALL DE CARDOS"),
        ("VALL D'EN BAS, LA"),
        ("VALLBONA D'ANOIA"),
        ("VALLBONA DE LES MONGES"),
        ("VALLCEBRE"),
        ("VALLCLARA"),
        ("VALLFOGONA DE BALAGUER"),
        ("VALLFOGONA DE RIPOLLES"),
        ("VALLFOGONA DE RIUCORB"),
        ("VALLGORGUINA"),
        ("VALLIRANA"),
        ("VALL-LLOBREGA"),
        ("VALLMOLL"),
        ("VALLROMANES"),
        ("VALLS"),
        ("VALLS D'AGUILAR, LES"),
        ("VALLS DE VALIRA, LES"),
        ("VANDELLOS I L'HOSPITALET DE L'INFANT"),
        ("VANSA I FORNOLS, LA"),
        ("VECIANA"),
        ("VENDRELL, EL"),
        ("VENTALLO"),
        ("VERDU"),
        ("VERGES"),
        ("VESPELLA DE GAIA"),
        ("VIC"),
        ("VIDRA"),
        ("VIDRERES"),
        ("VIELHA E MIJARAN"),
        ("VILABELLA"),
        ("VILABERTRAN"),
        ("VILABLAREIX"),
        ("VILADA"),
        ("VILADAMAT"),
        ("VILADASENS"),
        ("VILADECANS"),
        ("VILADECAVALLS"),
        ("VILADEMULS"),
        ("VILADRAU"),
        ("VILAFANT"),
        ("VILAFRANCA DEL PENEDES"),
        ("VILAGRASSA"),
        ("VILAJUIGA"),
        ("VILALBA DELS ARCS"),
        ("VILALBA SASSERRA"),
        ("VILALLER"),
        ("VILALLONGA DE TER"),
        ("VILALLONGA DEL CAMP"),
        ("VILAMACOLUM"),
        ("VILAMALLA"),
        ("VILAMANISCLE"),
        ("VILAMOS"),
        ("VILANANT"),
        ("VILANOVA DE BELLPUIG"),
        ("VILANOVA DE LA BARCA"),
        ("VILANOVA DE L'AGUDA"),
        ("VILANOVA DE MEIA"),
        ("VILANOVA DE PRADES"),
        ("VILANOVA DE SAU"),
        ("VILANOVA DE SEGRIA"),
        ("VILANOVA DEL CAMI"),
        ("VILANOVA DEL VALLES"),
        ("VILANOVA D'ESCORNALBOU"),
        ("VILANOVA I LA GELTRU"),
        ("VILAPLANA"),
        ("VILA-RODONA"),
        ("VILA-SACRA"),
        ("VILA-SANA"),
        ("VILA-SECA"),
        ("VILASSAR DE DALT"),
        ("VILASSAR DE MAR"),
        ("VILAUR"),
        ("VILAVERD"),
        ("VILELLA ALTA, LA"),
        ("VILELLA BAIXA, LA"),
        ("VILOBI DEL PENEDES"),
        ("VILOBI D'ONYAR"),
        ("VILOPRIU"),
        ("VILOSELL, EL"),
        ("VIMBODI I POBLET"),
        ("VINAIXA"),
        ("VINEBRE"),
        ("VINYOLS I ELS ARCS"),
        ("VIVER I SERRATEIX"),
        ("XERTA"),
    ]


