# Generated by Django 2.1.3 on 2019-06-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportsCorrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('subsidy_period', models.CharField(choices=[('2017', '2016-2017'), ('2018', '2017-2018'), ('2019', '2018-2019')], default=2019, max_length=4, verbose_name='convocatòria')),
                ('correlated_field', models.CharField(choices=[('Eix', 'Eix')], max_length=100, verbose_name='camp')),
                ('original_data', models.CharField(help_text='Valor del camp al back-office.', max_length=200, verbose_name='dada original')),
                ('correlated_data', models.CharField(help_text="Com ha de quedar el valor quan l'exportem per la justificació.", max_length=200, verbose_name='dada correlacionada')),
            ],
            options={
                'verbose_name': 'correlació',
                'verbose_name_plural': 'correlacions',
                'ordering': ['-subsidy_period'],
            },
        ),
        migrations.AlterField(
            model_name='dataexports',
            name='subsidy_period',
            field=models.CharField(choices=[('2017', '2016-2017'), ('2018', '2017-2018'), ('2019', '2018-2019')], default=2019, max_length=4, verbose_name='convocatòria'),
        ),
    ]
