# Generated by Django 2.1.3 on 2019-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0002_auto_20190615_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataexportscorrelation',
            options={'ordering': ['-subsidy_period', 'correlated_field', 'original_data'], 'verbose_name': 'correlació', 'verbose_name_plural': 'correlacions'},
        ),
        migrations.AlterField(
            model_name='dataexportscorrelation',
            name='correlated_field',
            field=models.CharField(choices=[('axis', 'Eix'), ('stage_type', "Tipus d'acompanyament"), ('gender', 'Gènere'), ('minors_grade', "Grau d'estudis")], max_length=100, verbose_name='camp'),
        ),
    ]
