# Generated by Django 2.1.3 on 2019-07-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0005_auto_20190701_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataExportsCorrelation',
        ),
    ]
