# Generated by Django 2.0 on 2019-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0006_delete_dataexportscorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexports',
            name='subsidy_period',
            field=models.CharField(choices=[('2017', '2016-2017'), ('2018', '2017-2018'), ('2019', '2018-2019'), ('2020', '2019-2020')], default=2019, max_length=4, verbose_name='convocatòria'),
        ),
    ]
