# Generated by Django 2.2.7 on 2020-01-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0008_subsidyperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexports',
            name='subsidy_period_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.SubsidyPeriod'),
        ),
    ]
