# Generated by Django 2.2.7 on 2020-01-21 11:13

from django.db import migrations


def populate_exports(apps, schema_editor):
    """
    Previosly the populatebasedata command was loading a json with the 2018-2019 export registry.
    After changing the DataExports model structure, this stopped working. This replaces it with the proper
    data migration.
    Also it adds the temporary migration for 2019-2020.
    """
    SubsidyPeriod = apps.get_model('dataexports', 'SubsidyPeriod')
    DataExports = apps.get_model('dataexports', 'DataExports')

    p2019, created = SubsidyPeriod.objects.get_or_create(name="2018-2019")
    if created:
        r = DataExports(
            name="Exportació de totes les dades en un sol fitxer",
            function_name="export_2018_2019",
            ignore_errors=True,
            subsidy_period=p2019
        )
        r.save()
        print("")
        print("Exportacio de dades de la convocatòria 2018-2019 creada.")
    else:
        print("L'exportació de 2018-2019 ja existeix.")

    p2020, created = SubsidyPeriod.objects.get_or_create(name="2019-2020")
    if created:
        r = DataExports(
            name="Exportació provisional 2019-2020",
            function_name="export_2019_2020",
            ignore_errors=True,
            subsidy_period=p2020,
            notes="És una rèplica de la de 2018-2019, fins que no tinguem el nou format, aquesta exportació només serveix "
                  "per poder fer seguiment."
        )
        r.save()
        print("Exportacio de dades PROVISIONAL per la convocatòria 2019-2020 creada.")
    else:
        print("L'exportació de 2019-2020 ja existeix.")


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0011_restore_transfered_field_name'),
    ]

    operations = [
        migrations.RunPython(populate_exports),
    ]
