# Generated by Django 2.2.7 on 2020-01-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0012_populate_2019_and_2020_exports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexports',
            name='subsidy_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.SubsidyPeriod', verbose_name='convocatòria'),
        ),
    ]
