# Generated by Django 2.2.7 on 2020-08-07 14:02

from django.db import migrations


def cofunded_export(apps, schema_editor):
    print('')
    mail_model = apps.get_model('dataexports', 'DataExports')
    subsidy_model = apps.get_model('dataexports', 'SubsidyPeriod')
    period_obj = subsidy_model.objects.get(name__exact='2019-2020')

    obj, created = mail_model.objects.update_or_create(
        function_name='export_cofunded_2019_2020',
        defaults={
            'subsidy_period': period_obj,
            'name': 'Cofinançades',
            'function_name': 'export_cofunded_2019_2020',
            'ignore_errors': True
        }
    )
    print("Exportació de Cofinançades creada")

    obj, created = mail_model.objects.update_or_create(
        function_name='export_stages_descriptions',
        defaults={
            'subsidy_period': period_obj,
            'name': 'Memòria dels acompanyaments en fitxer de text',
            'function_name': 'export_stages_descriptions',
            'ignore_errors': True
        }
    )
    print("Exportació de Memòria d'acompanyaments en text creada")


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0014_auto_20200616_1407'),
    ]

    operations = [
        migrations.RunPython(cofunded_export),
    ]
