# Generated by Django 2.2.7 on 2021-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0016_auto_20200915_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexports',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
    ]
