# Generated by Django 3.2.14 on 2022-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'població',
                'verbose_name_plural': 'poblacions',
                'ordering': ['name'],
            },
        ),
    ]
