# Generated by Django 2.1.3 on 2019-03-11 19:59

import cc_users.managers
import coopolis.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('cc_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correu electrònic')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, null=True, verbose_name="nom d'usuari/a")),
                ('surname2', models.CharField(blank=True, max_length=50, null=True, verbose_name='segon cognom')),
                ('id_number', models.CharField(max_length=11, null=True, verbose_name='DNI o NIE')),
                ('gender', models.CharField(blank=True, choices=[('OTHER', 'Altre'), ('FEMALE', 'Dona'), ('MALE', 'Home')], max_length=10, null=True, verbose_name='gènere')),
                ('birth_place', models.TextField(blank=True, choices=[('BARCELONA', 'Barcelona'), ('CATALUNYA', 'Catalunya'), ('ESPANYA', 'Espanya'), ('OTHER', 'Altre')], null=True, verbose_name='lloc de naixement')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='data de naixement')),
                ('residence_district', models.TextField(blank=True, choices=[('CV', 'Ciutat Vella'), ('EX', 'Eixample'), ('HG', 'Horta-Guinardó'), ('LC', 'Les Corts'), ('NB', 'Nou Barris'), ('SA', 'Sant Andreu'), ('SM', 'Sant Martí'), ('ST', 'Sants-Montjuïc'), ('SS', 'Sarrià-Sant Gervasi'), ('GR', 'Gràcia')], null=True, verbose_name='barri')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='adreça')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='telèfon')),
                ('educational_level', models.TextField(blank=True, choices=[('MASTER', 'Màster / Postgrau'), ('HIGH_SCHOOL', 'Secundària'), ('WITHOUT_STUDIES', 'Sense estudis'), ('FP', 'Formació professional'), ('UNIVERSITY', 'Estudis universitaris'), ('ELEMENTARY_SCHOOL', 'Primària')], null=True, verbose_name="nivell d'estudis")),
                ('employment_situation', models.TextField(blank=True, choices=[('SELF_EMPLOYED', 'En actiu per compte propi'), ('UNEMPLOYMENT_BENEFIT_RECEIVER', 'Perceptora de prestacions socials'), ('UNEMPLOYMENT_BENEFIT_REQUESTED', "Demandant d'ocupació"), ('EMPLOYED_WORKER', 'En actiu per compte aliè')], null=True, verbose_name='situació laboral')),
                ('discovered_us', models.TextField(blank=True, choices=[('INTERNET', 'Per internet i xarxes socials'), ('FRIEND', "A través d'un conegut"), ('PREVIOUS_ACTIVITY', 'Per una activitat de Coòpolis'), ('OTHER', 'Altres')], null=True, verbose_name='com ens has conegut')),
                ('cooperativism_knowledge', models.TextField(blank=True, help_text='Tens coneixements / formació / experiència en cooperativisme? Quina? Cursos realitzats?', null=True, verbose_name='coneixements previs')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'persones',
            },
            managers=[
                ('objects', cc_users.managers.CCUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('sector', models.CharField(choices=[('A', 'Altres'), ('C', 'Comunicació i tecnologia'), ('F', 'Finances'), ('O', 'Oci'), ('H', 'Habitatge'), ('L', 'Logística'), ('E', 'Educació'), ('C', 'Cultura'), ('S', 'Assessorament'), ('M', 'Alimentació'), ('U', 'Cures'), ('R', 'Roba')], max_length=2)),
                ('web', models.CharField(blank=True, max_length=200, verbose_name='Web')),
                ('project_status', models.CharField(blank=True, choices=[('IN_MEDITATION_PROCESS', 'En proces de debat/reflexió'), ('IN_CONSTITUTION_PROCESS', 'En constitució'), ('RUNNING', 'En funcionament')], max_length=50, null=True, verbose_name='estat del projecte')),
                ('motivation', models.CharField(blank=True, choices=[('COOPERATIVISM_EDUCATION', 'Formació en cooperativisme'), ('COOPERATIVE_CREATION', "Constitució d'una cooperativa"), ('TRANSFORM_FROM_ASSOCIATION', "Transformació d'associació a coopetiva"), ('TRANSFORM_FROM_SCP', 'Transformació de SCP a coopertiva'), ('ENTERPRISE_RELIEF', 'Relleu empresarial'), ('CONSOLIDATION', 'Consolidació'), ('OTHER', 'Altres')], max_length=50, null=True, verbose_name='petició inicial')),
                ('mail', models.EmailField(max_length=254, verbose_name='correu electrònic')),
                ('phone', models.CharField(max_length=25, verbose_name='telèfon')),
                ('district', models.TextField(blank=True, choices=[('CV', 'Ciutat Vella'), ('EX', 'Eixample'), ('HG', 'Horta-Guinardó'), ('LC', 'Les Corts'), ('NB', 'Nou Barris'), ('SA', 'Sant Andreu'), ('SM', 'Sant Martí'), ('ST', 'Sants-Montjuïc'), ('SS', 'Sarrià-Sant Gervasi'), ('GR', 'Gràcia')], null=True, verbose_name='districte')),
                ('number_people', models.IntegerField(blank=True, null=True, verbose_name='número de persones')),
                ('registration_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='data de registre')),
                ('cif', models.CharField(blank=True, max_length=11, null=True, verbose_name='N.I.F.')),
                ('object_finality', models.TextField(blank=True, null=True, verbose_name='objecte i finalitat')),
                ('project_origins', models.TextField(blank=True, null=True, verbose_name='orígens del projecte')),
                ('solves_necessities', models.TextField(blank=True, null=True, verbose_name='quines necessitats resol el vostre projecte?')),
                ('social_base', models.TextField(blank=True, null=True, verbose_name='compta el vostre projecte amb una base social?')),
                ('constitution_date', models.DateField(blank=True, null=True, verbose_name='data de constitució')),
                ('estatuts', models.FileField(blank=True, max_length=250, null=True, verbose_name='estatuts')),
                ('viability', models.FileField(blank=True, max_length=250, null=True, verbose_name='pla de viabilitat')),
                ('sostenibility', models.FileField(blank=True, max_length=250, null=True, verbose_name='pla de sostenibilitat')),
            ],
            options={
                'verbose_name': 'projecte',
                'verbose_name_plural': 'projectes',
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy_period', models.CharField(blank=True, choices=[('2018', '2017-2018'), ('2019', '2018-2019')], default=2019, max_length=4, null=True, verbose_name='convocatòria')),
                ('date_start', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="data d'inici")),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='data de finalització')),
                ('follow_up', models.TextField(blank=True, null=True, verbose_name='seguiment')),
                ('axis', models.CharField(blank=True, choices=[('B', 'Eix B'), ('C', 'Eix C'), ('D', 'Eix D')], help_text='Eix de la convocatòria on es justificarà.', max_length=1, null=True, verbose_name='eix')),
                ('scanned_signatures', models.FileField(blank=True, max_length=250, null=True, verbose_name='document amb signatures')),
                ('involved_partners', models.ManyToManyField(blank=True, related_name='stage_involved_partners', to=settings.AUTH_USER_MODEL, verbose_name='persones involucrades')),
                ('organizer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity', verbose_name='qui ho fa')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coopolis.Project', verbose_name='acompanyament')),
                ('stage_responsible', models.ForeignKey(blank=True, help_text="Persona de l'equip al càrrec de l'acompanyament. Per aparèixer al desplegable, cal que la persona tingui activada la opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_responsible', to=settings.AUTH_USER_MODEL, verbose_name='persona responsable')),
            ],
            options={
                'verbose_name': 'acompanyament',
                'verbose_name_plural': 'acompanyaments',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': "tipus d'acompanyament",
                'verbose_name_plural': "tipus d'acompanyaments",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'població',
                'verbose_name_plural': 'poblacions',
            },
        ),
        migrations.AddField(
            model_name='projectstage',
            name='stage_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='coopolis.ProjectStageType', verbose_name="tipus d'acompanyament"),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Town'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
