# Generated by Django 2.1.3 on 2019-02-25 16:02

import cc_users.managers
import coopolis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correu electrònic')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, null=True, verbose_name="Nom d'usuari/a")),
                ('surname2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segon cognom')),
                ('id_number', models.CharField(max_length=11, null=True, verbose_name='DNI o NIE')),
                ('gender', models.CharField(blank=True, choices=[('OTHER', 'Altre'), ('FEMALE', 'Dona'), ('MALE', 'Home')], max_length=10, null=True, verbose_name='Gènere')),
                ('birth_place', models.TextField(blank=True, choices=[('BARCELONA', 'Barcelona'), ('CATALUNYA', 'Catalunya'), ('ESPANYA', 'Espanya'), ('OTHER', 'Altre')], null=True, verbose_name='Lloc de naixement')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de naixement')),
                ('residence_district', models.TextField(blank=True, choices=[('CV', 'Ciutat Vella'), ('EX', 'Eixample'), ('HG', 'Horta-Guinardó'), ('LC', 'Les Corts'), ('NB', 'Nou Barris'), ('SA', 'Sant Andreu'), ('SM', 'Sant Martí'), ('ST', 'Sants-Montjuïc'), ('SS', 'Sarrià-Sant Gervasi'), ('GR', 'Gràcia')], null=True, verbose_name='Barri')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Adreça')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telèfon')),
                ('educational_level', models.TextField(blank=True, choices=[('MASTER', 'Màster / Postgrau'), ('HIGH_SCHOOL', 'Secundària'), ('WITHOUT_STUDIES', 'Sense estudis'), ('FP', 'Formació professional'), ('UNIVERSITY', 'Estudis universitaris'), ('ELEMENTARY_SCHOOL', 'Primària')], null=True, verbose_name="Nivell d'estudis")),
                ('employment_situation', models.TextField(blank=True, choices=[('SELF_EMPLOYED', 'En actiu per compte propi'), ('UNEMPLOYMENT_BENEFIT_RECEIVER', 'Perceptora de prestacions socials'), ('UNEMPLOYMENT_BENEFIT_REQUESTED', "Demandant d'ocupació"), ('EMPLOYED_WORKER', 'En actiu per compte aliè')], null=True, verbose_name='Situació laboral')),
                ('discovered_us', models.TextField(blank=True, choices=[('INTERNET', 'Per internet i xarxes socials'), ('FRIEND', "A través d'un conegut"), ('PREVIOUS_ACTIVITY', 'Per una activitat de Coòpolis'), ('OTHER', 'Altres')], null=True, verbose_name='Com ens has conegut')),
                ('cooperativism_knowledge', models.TextField(blank=True, help_text='Tens coneixements / formació / experiència en cooperativisme? Quina? Cursos realitzats?', null=True, verbose_name='Coneixements previs')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persones',
            },
            managers=[
                ('objects', cc_users.managers.CCUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('sector', models.CharField(choices=[('A', 'Altres'), ('C', 'Comunicació i tecnologia'), ('F', 'Finances'), ('O', 'Oci'), ('H', 'Habitatge'), ('L', 'Logística'), ('E', 'Educació'), ('C', 'Cultura'), ('S', 'Assessorament'), ('M', 'Alimentació'), ('U', 'Cures'), ('R', 'Roba')], max_length=2)),
                ('web', models.CharField(blank=True, max_length=200, verbose_name='Web')),
                ('project_status', models.CharField(blank=True, choices=[('IN_MEDITATION_PROCESS', 'En proces de debat/reflexió'), ('IN_CONSTITUTION_PROCESS', 'En constitució'), ('RUNNING', 'En funcionament')], max_length=50, null=True, verbose_name='Estat del projecte')),
                ('motivation', models.CharField(blank=True, choices=[('COOPERATIVISM_EDUCATION', 'Formació en cooperativimse'), ('COOPERATIVE_CREATION', "Constitució d'una cooperativa"), ('TRANSFORM_FROM_ASSOCIATION', "Transformació d'associació a coopetiva"), ('TRANSFORM_FROM_SCP', 'Transformació de SCP a coopertiva'), ('ENTERPRISE_RELIEF', 'Relleu empresarial'), ('CONSOLIDATION', 'Consolidació'), ('OTHER', 'Altres')], max_length=50, null=True, verbose_name='Petició inicial')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correu electrònic')),
                ('phone', models.CharField(max_length=25, verbose_name='Telèfon')),
                ('district', models.TextField(blank=True, choices=[('CV', 'Ciutat Vella'), ('EX', 'Eixample'), ('HG', 'Horta-Guinardó'), ('LC', 'Les Corts'), ('NB', 'Nou Barris'), ('SA', 'Sant Andreu'), ('SM', 'Sant Martí'), ('ST', 'Sants-Montjuïc'), ('SS', 'Sarrià-Sant Gervasi'), ('GR', 'Gràcia')], null=True, verbose_name='Districte')),
                ('number_people', models.IntegerField(blank=True, null=True, verbose_name='Número de persones')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Data de registre')),
                ('cif', models.CharField(blank=True, max_length=11, null=True, verbose_name='NIF')),
                ('subsidy_period', models.TextField(blank=True, choices=[('2018', '2018'), ('2019', '2019')], null=True, verbose_name='Convocatòria')),
                ('object_finality', models.TextField(blank=True, null=True, verbose_name='Objecte i finalitat')),
                ('project_origins', models.TextField(blank=True, null=True, verbose_name='Orígens del projecte')),
                ('solves_necessities', models.TextField(blank=True, null=True, verbose_name='Quines necessitats resol el vostre projecte?')),
                ('social_base', models.TextField(blank=True, null=True, verbose_name='Compta el vostre projecte amb una base social?')),
                ('constitution_date', models.DateField(blank=True, null=True, verbose_name='Data de constitució')),
                ('estatuts', models.FileField(blank=True, max_length=250, null=True, upload_to=coopolis.models.estatuts_upload_path, verbose_name='Estatuts')),
                ('viability', models.FileField(blank=True, max_length=250, null=True, upload_to=coopolis.models.estatuts_upload_path, verbose_name='Pla de viabilitat')),
                ('sostenibility', models.FileField(blank=True, max_length=250, null=True, upload_to=coopolis.models.estatuts_upload_path, verbose_name='Pla de sostenibilitat')),
                ('project_responsible', models.ForeignKey(blank=True, help_text="Persona de l'equip al càrrec de l'acompanyament. Per aparèixer al desplegable, cal que la persona tingui activada la opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Persona responsable')),
            ],
            options={
                'verbose_name': 'Projecte',
                'verbose_name_plural': 'Projectes',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Població',
                'verbose_name_plural': 'Poblacions',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Project', verbose_name='Projecte'),
        ),
        migrations.AddField(
            model_name='user',
            name='residence_town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Town'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
