# Generated by Django 2.1.3 on 2019-02-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='adreca_tipus_via',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adreca_tipus_via',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='adreca_bloc',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='adreca_nom_via',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='adreca_numero',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='adreca_planta',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='adreca_porta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adreca_bloc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adreca_nom_via',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adreca_numero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adreca_planta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adreca_porta',
        ),
    ]
