# Generated by Django 2.1.3 on 2019-02-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='residence_town',
            new_name='town',
        ),
    ]
