# Generated by Django 2.1.3 on 2019-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0002_auto_20190220_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adreça'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adreça'),
        ),
    ]
