# Generated by Django 2.1.3 on 2019-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0003_auto_20190410_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('IN_MEDITATION_PROCESS', 'En proces de debat/reflexió'), ('IN_CONSTITUTION_PROCESS', 'En constitució'), ('RUNNING', 'En funcionament'), ('DOWN', 'Caigut')], max_length=50, null=True, verbose_name='estat del projecte'),
        ),
    ]
