# Generated by Django 2.1.3 on 2019-02-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0003_auto_20190222_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Població',
                'verbose_name_plural': 'Poblacions',
            },
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='sector',
            field=models.CharField(choices=[('A', 'Altres'), ('C', 'Comunicació i tecnologia'), ('F', 'Finances'), ('O', 'Oci'), ('H', 'Habitatge'), ('L', 'Logística'), ('E', 'Educació'), ('C', 'Cultura'), ('S', 'Assessorament'), ('M', 'Alimentació'), ('U', 'Cures'), ('R', 'Roba')], max_length=2),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='id_number',
            field=models.CharField(max_length=11, null=True, verbose_name='DNI o NIE'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='residence_town',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='coopolis.Town'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name="Nom d'usuari/a"),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(choices=[('A', 'Altres'), ('C', 'Comunicació i tecnologia'), ('F', 'Finances'), ('O', 'Oci'), ('H', 'Habitatge'), ('L', 'Logística'), ('E', 'Educació'), ('C', 'Cultura'), ('S', 'Assessorament'), ('M', 'Alimentació'), ('U', 'Cures'), ('R', 'Roba')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=11, null=True, verbose_name='DNI o NIE'),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence_town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Town'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name="Nom d'usuari/a"),
        ),
    ]
