# Generated by Django 2.1.3 on 2019-03-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0003_auto_20190306_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='stage_responsible',
            field=models.ForeignKey(blank=True, help_text="Persona de l'equip al càrrec de l'acompanyament. Per aparèixer al desplegable, cal que la persona tingui activada la opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Persona responsable'),
        ),
    ]
