# Generated by Django 2.1.3 on 2019-02-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0004_auto_20190223_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adreça'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adreça'),
        ),
    ]
