# Generated by Django 2.1.3 on 2019-03-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0004_projectstage_stage_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstage',
            options={'ordering': ['-date_start'], 'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_responsible',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subsidy_period',
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coopolis.Project', verbose_name='Projecte'),
        ),
    ]
