# Generated by Django 2.1.3 on 2019-02-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0005_auto_20190223_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(blank=True, choices=[('OTHER', 'Altre'), ('FEMALE', 'Dona'), ('MALE', 'Home')], max_length=10, null=True, verbose_name='Gènere'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('OTHER', 'Altre'), ('FEMALE', 'Dona'), ('MALE', 'Home')], max_length=10, null=True, verbose_name='Gènere'),
        ),
    ]
