# Generated by Django 2.1.3 on 2019-04-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0005_auto_20190415_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Town', verbose_name='població'),
        ),
    ]
