# Generated by Django 2.1.3 on 2019-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0005_auto_20190307_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='organizer',
            field=models.CharField(blank=True, choices=[('AT', 'Ateneu'), ('CM', 'Cercle Migracions'), ('CI', 'Cercle Incubació'), ('CC', 'Cercle Consum')], max_length=2, null=True, verbose_name='Qui ho fa'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='subsidy_period',
            field=models.CharField(blank=True, choices=[('2018', '2017-2018'), ('2019', '2018-2019')], default=2019, max_length=4, null=True, verbose_name='Convocatòria'),
        ),
    ]
