# Generated by Django 2.1.3 on 2019-02-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0006_auto_20190225_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='birth_place',
            field=models.TextField(blank=True, choices=[('BARCELONA', 'Barcelona'), ('CATALUNYA', 'Catalunya'), ('ESPANYA', 'Espanya'), ('OTHER', 'Altre')], null=True, verbose_name='Lloc de naixement'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='discovered_us',
            field=models.TextField(blank=True, choices=[('INTERNET', 'Per internet i xarxes socials'), ('FRIEND', "A través d'un conegut"), ('PREVIOUS_ACTIVITY', 'Per una activitat de Coòpolis'), ('OTHER', 'Altres')], null=True, verbose_name='Com ens has conegut'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='educational_level',
            field=models.TextField(blank=True, choices=[('MASTER', 'Màster / Postgrau'), ('HIGH_SCHOOL', 'Secundària'), ('WITHOUT_STUDIES', 'Sense estudis'), ('FP', 'Formació professional'), ('UNIVERSITY', 'Estudis universitaris'), ('ELEMENTARY_SCHOOL', 'Primària')], null=True, verbose_name="Nivell d'estudis"),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='employment_situation',
            field=models.TextField(blank=True, choices=[('SELF_EMPLOYED', 'En actiu per compte propi'), ('UNEMPLOYMENT_BENEFIT_RECEIVER', 'Perceptora de prestacions socials'), ('UNEMPLOYMENT_BENEFIT_REQUESTED', "Demandant d'ocupació"), ('EMPLOYED_WORKER', 'En actiu per compte aliè')], null=True, verbose_name='Situació laboral'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_place',
            field=models.TextField(blank=True, choices=[('BARCELONA', 'Barcelona'), ('CATALUNYA', 'Catalunya'), ('ESPANYA', 'Espanya'), ('OTHER', 'Altre')], null=True, verbose_name='Lloc de naixement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discovered_us',
            field=models.TextField(blank=True, choices=[('INTERNET', 'Per internet i xarxes socials'), ('FRIEND', "A través d'un conegut"), ('PREVIOUS_ACTIVITY', 'Per una activitat de Coòpolis'), ('OTHER', 'Altres')], null=True, verbose_name='Com ens has conegut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='educational_level',
            field=models.TextField(blank=True, choices=[('MASTER', 'Màster / Postgrau'), ('HIGH_SCHOOL', 'Secundària'), ('WITHOUT_STUDIES', 'Sense estudis'), ('FP', 'Formació professional'), ('UNIVERSITY', 'Estudis universitaris'), ('ELEMENTARY_SCHOOL', 'Primària')], null=True, verbose_name="Nivell d'estudis"),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_situation',
            field=models.TextField(blank=True, choices=[('SELF_EMPLOYED', 'En actiu per compte propi'), ('UNEMPLOYMENT_BENEFIT_RECEIVER', 'Perceptora de prestacions socials'), ('UNEMPLOYMENT_BENEFIT_REQUESTED', "Demandant d'ocupació"), ('EMPLOYED_WORKER', 'En actiu per compte aliè')], null=True, verbose_name='Situació laboral'),
        ),
    ]
