# Generated by Django 2.1.3 on 2019-05-31 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0006_auto_20190428_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='sòcies'),
        ),
    ]
