# Generated by Django 2.1.3 on 2019-03-08 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0006_auto_20190307_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registration_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data de registre'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Data d'inici"),
        ),
    ]
