# Generated by Django 2.1.3 on 2019-03-08 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0008_auto_20190308_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='involved_partners',
            field=models.ManyToManyField(related_name='stage_involved_partners', to=settings.AUTH_USER_MODEL, verbose_name='Persones involucrades'),
        ),
    ]
