# Generated by Django 2.1.3 on 2019-06-03 15:27

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def add_group_permissions(apps, schema_editor):
    #base user
    group, created = Group.objects.get_or_create(name='Permisos base')
    if created:
        add_thing = Permission.objects.filter(
            codename__in=['add_logentry', 'change_logentry', 'view_logentry', 'delete_logentry', 'view_permission',
                      'add_town', 'change_town', 'delete_town', 'view_town', 'add_user', 'change_user',
                      'view_user',]
        )
        group.permissions.set(add_thing)
        group.save()
        print('Grup Permisos base creat.')

    #formació
    group, created = Group.objects.get_or_create(name="Gestió d'accions i sessions")
    if created:
        add_thing = Permission.objects.filter(
            codename__in=['add_activity', 'change_activity', 'delete_activity', 'view_activity', 'add_course',
                              'change_course', 'delete_course', 'view_course', 'add_courseplace', 'change_courseplace',
                              'delete_courseplace', 'view_courseplace', 'view_entity', 'add_organizer',
                              'change_organizer', 'delete_organizer', 'view_organizer', 'add_attachment',
                              'change_attachment', 'delete_attachment', 'view_attachment', 'add_source',
                              'change_source', 'delete_source', 'view_source', 'add_thumbnail', 'change_thumbnail',
                              'delete_thumbnail', 'view_thumbnail', 'add_thumbnaildimensions',
                              'change_thumbnaildimensions', 'delete_thumbnaildimensions', 'view_thumbnaildimensions']
        )
        group.permissions.set(add_thing)
        group.save()
        print("Grup Gestió d'accions i sessions creat")

    #projectes
    group, created = Group.objects.get_or_create(name='Gestió de projectes')
    if created:
        add_thing = Permission.objects.filter(
            codename__in=['add_project', 'change_project', 'view_project', 'add_projectstagetype',
                              'change_projectstagetype', 'delete_projectstagetype', 'view_projectstagetype',
                              'view_projectstagetype']
        )
        group.permissions.set(add_thing)
        group.save()
        print("Grup Gestió de projectes creat")


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0009_auto_20190603_1302'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
