# Generated by Django 2.1.3 on 2019-03-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0009_auto_20190308_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstage',
            options={'ordering': ['-date_start'], 'verbose_name': 'Acompanyament', 'verbose_name_plural': 'Acompanyaments'},
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coopolis.Project', verbose_name='Acompanyament'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage',
            field=models.CharField(choices=[('REQUESTED', 'Acompanyament sol·licitat'), ('CONSTITUTION', 'Constitució'), ('CONSOLIDATION', 'Consolidació')], default='REQUESTED', max_length=50, verbose_name="Tipus d'acompanyament"),
        ),
    ]
