# Generated by Django 2.1.3 on 2019-06-21 11:55

import coopolis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0010_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='scanned_certificate',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='certificat'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='scanned_signatures',
            field=models.FileField(blank=True, max_length=250, null=True, verbose_name='fitxa de projectes (document amb signatures)'),
        ),
    ]
