# Generated by Django 2.1.3 on 2019-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0010_auto_20190311_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': "tipus d'acompanyament",
                'verbose_name_plural': "tipus d'acompanyaments",
                'ordering': ['name'],
            },
        ),
    ]
