# Generated by Django 2.1.3 on 2019-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0011_auto_20190621_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fake_email',
            field=models.BooleanField(default=False, help_text='Marca aquesta casella si el correu és inventat, i desmarca-la si mai el canvieu pel correu real. Ens ajudarà a mantenir la base de dadesneta.', verbose_name='e-mail inventat'),
        ),
    ]
