# Generated by Django 2.1.3 on 2019-03-11 18:16

from django.db import migrations


def create_stage_types(apps, schema_editor):
    model = apps.get_model('coopolis', 'ProjectStageType')
    model.objects.bulk_create([
        model(name="Acompanyament sol·licitat"),
        model(name="Constitució"),
        model(name="Consolidació")
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0011_projectstagetype'),
    ]

    operations = [
        migrations.RunPython(create_stage_types),
    ]
