# Generated by Django 2.1.3 on 2019-03-11 18:36

import coopolis.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0012_auto_20190311_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstage',
            options={'ordering': ['-date_start'], 'verbose_name': 'acompanyament', 'verbose_name_plural': 'acompanyaments'},
        ),
        migrations.RemoveField(
            model_name='projectstage',
            name='stage',
        ),
        migrations.AddField(
            model_name='projectstage',
            name='stage_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='coopolis.ProjectStageType', verbose_name="tipus d'acompanyament"),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='axis',
            field=models.CharField(blank=True, choices=[('B', 'Eix B'), ('C', 'Eix C'), ('D', 'Eix D')], help_text='Eix de la convocatòria on es justificarà.', max_length=1, null=True, verbose_name='eix'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='data de finalització'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="data d'inici"),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='follow_up',
            field=models.TextField(blank=True, null=True, verbose_name='seguiment'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='involved_partners',
            field=models.ManyToManyField(blank=True, related_name='stage_involved_partners', to=settings.AUTH_USER_MODEL, verbose_name='persones involucrades'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='organizer',
            field=models.CharField(blank=True, choices=[('AT', 'Ateneu'), ('CM', 'Cercle Migracions'), ('CI', 'Cercle Incubació'), ('CC', 'Cercle Consum')], max_length=2, null=True, verbose_name='qui ho fa'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coopolis.Project', verbose_name='acompanyament'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='scanned_signatures',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=coopolis.models.stage_signatures_upload_path, verbose_name='document amb signatures'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage_responsible',
            field=models.ForeignKey(blank=True, help_text="Persona de l'equip al càrrec de l'acompanyament. Per aparèixer al desplegable, cal que la persona tingui activada la opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_responsible', to=settings.AUTH_USER_MODEL, verbose_name='persona responsable'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='subsidy_period',
            field=models.CharField(blank=True, choices=[('2018', '2017-2018'), ('2019', '2018-2019')], default=2019, max_length=4, null=True, verbose_name='convocatòria'),
        ),
    ]
