# Generated by Django 2.1.3 on 2019-07-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0014_auto_20190724_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Town', verbose_name='població'),
        ),
    ]
