# Generated by Django 2.1.3 on 2019-07-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0015_project_town'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='residence_district',
            new_name='district',
        ),
    ]
