# Generated by Django 2.0.13 on 2019-08-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0018_projectstage_subaxis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='subaxis',
            field=models.CharField(blank=True, help_text="Correspon a 'Tipus d'acció' a la justificació.", max_length=2, null=True, verbose_name='sub-eix'),
        ),
    ]
