# Generated by Django 2.0 on 2019-11-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0024_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='coopolis.Project', verbose_name='projecte acompanyat'),
        ),
    ]
