# Generated by Django 2.0 on 2019-11-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0027_auto_20191119_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='derivation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.Derivation', verbose_name='derivat'),
        ),
    ]
