# Generated by Django 2.0 on 2019-11-20 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0028_auto_20191119_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentInsertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertion_date', models.DateField(verbose_name='alta seguretat social')),
                ('contract_type', models.CharField(choices=[('autonom', 'Autònom -RETA-'), ('general_cpropi', 'Règim general - compte propi'), ('general_calie', 'Règim general - compte aliè')], max_length=50, verbose_name='tipus de contracte')),
                ('duration', models.CharField(choices=[('indefinit', 'Indefinit'), ('obraservei', 'Obra i servei'), ('temporal', 'Temporal')], max_length=50, verbose_name='durada')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_insertions', to='coopolis.Project', verbose_name='projecte acompanyat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='persona')),
            ],
            options={
                'verbose_name': 'inserció laboral',
                'verbose_name_plural': 'insercions laborals',
                'ordering': ['-insertion_date'],
            },
        ),
    ]
