# Generated by Django 2.2.7 on 2019-11-20 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0029_employmentinsertion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='involved_partners',
            field=models.ManyToManyField(blank=True, help_text="Persones que apareixeran a la justificació com a que han participat a l'acompanyament.", related_name='stage_involved_partners', to=settings.AUTH_USER_MODEL, verbose_name='persones involucrades'),
        ),
    ]
