# Generated by Django 2.2.7 on 2020-01-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0034_subsidy_period_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ProjectStage',
            name='subsidy_period',
        ),
        migrations.RenameField(
            model_name='ProjectStage',
            old_name='subsidy_period_link',
            new_name='subsidy_period',
        ),
    ]
