# Generated by Django 2.2.7 on 2020-01-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0012_populate_2019_and_2020_exports'),
        ('coopolis', '0037_auto_20200120_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinsertion',
            name='subsidy_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.SubsidyPeriod'),
        ),
    ]
