# Generated by Django 2.2.7 on 2020-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0042_user_groups_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='stage_type',
            field=models.CharField(choices=[('1', '00 Nova creació - acollida'), ('2', '01 Nova creació - procés'), ('6', '02 Nova creació - constitució'), ('7', '03 Consolidació - 1a acollida'), ('8', '04 Consolidació - acompanyament'), ('9', '05 Crisi Covid')], default=1, max_length=2, verbose_name="tipus d'acompanyament"),
        ),
    ]
