# Generated by Django 2.2.7 on 2020-04-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0044_auto_20200403_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorize_communications',
            field=models.BooleanField(default=False, verbose_name='autoritza comunicació publicitària'),
        ),
    ]
