# Generated by Django 2.2.7 on 2020-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0050_auto_20200505_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_involved',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name="si participes a un projecte cooperatiu o de l'ESS, indica'ns-el"),
        ),
    ]
