# Generated by Django 2.2.7 on 2020-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0053_projectsfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripció'),
        ),
        migrations.AddField(
            model_name='project',
            name='other',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='altres'),
        ),
    ]
