# Generated by Django 2.2.7 on 2020-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0056_projectsconstituted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='follow_up_situation',
            field=models.CharField(blank=True, choices=[('PENDENT', 'Pendent d’enviar proposta de trobada'), ('ENVIAT', 'Enviat email amb proposta de data per trobar-nos'), ('CONCERTADA', 'Data de trobada concertada'), ('ACOLLIT', 'Acollida realitzada'), ('PAUSA', 'Acompanyament en pausa'), ('CANCEL', 'Acompanyament cancel·lat')], max_length=50, null=True, verbose_name='seguiment'),
        ),
        migrations.AddField(
            model_name='project',
            name='follow_up_situation_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actualització seguiment'),
        ),
    ]
