# Generated by Django 2.2.7 on 2020-06-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0057_auto_20200611_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsfollowup',
            options={'ordering': ['follow_up_situation', 'follow_up_situation_update'], 'verbose_name': "Seguiment d'acompanyament", 'verbose_name_plural': "Seguiment d'acompanyaments"},
        ),
    ]
