# Generated by Django 2.2.7 on 2020-06-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0059_project_subsidy_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subsidy_period',
            field=models.ForeignKey(blank=True, help_text="OPCIONAL. En cas que el projecte s'hagi constituït en una convocatòria posterior a l'ultima intervenció de l'ateneu, podeu indicar-ho aquí, per tal que aparegui a l'informe de Projectes Constituïts. Aquest camp NO farà aparèixer el projecte a l'excel de justificació (per aparèixer a l'excel cal crear una Justificació d'Acompanyament)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.SubsidyPeriod', verbose_name='convocatòria de la constitució'),
        ),
    ]
