# Generated by Django 2.2.7 on 2020-08-05 17:11

from django.db import migrations


def migrate2020subaxis(apps, schema_editor):
    print('')
    # migrating activities's subaxis C3 to C4
    activity_obj = apps.get_model('cc_courses', 'Activity')
    qs = activity_obj.objects.filter(subaxis='C3')
    for obj in qs:
        obj.subaxis = 'C4'
        obj.save()
        print(obj)
    print('Sessions del sub-eix C3 passades a C4.')

    # migrating projectstages's subaxis C3 to C4
    project_stage_obj = apps.get_model('coopolis', 'ProjectStage')
    qs = project_stage_obj.objects.filter(subaxis='C3')
    for obj in qs:
        obj.subaxis = 'C4'
        obj.save()
        print(obj)
    print('Acompanyaments del sub-eix C3 passades a C4.')


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0066_auto_20200805_1911'),
    ]

    operations = [
        migrations.RunPython(migrate2020subaxis),
    ]
