# Generated by Django 2.2.7 on 2020-08-07 07:45

from django.db import migrations


def populate_mail_templates(apps, schema_editor):
    print('')
    mail_model = apps.get_model('mailing_manager', 'Mail')

    obj, created = mail_model.objects.update_or_create(
        text_identifier='EMAIL_ENROLLMENT_REMINDER',
        defaults={
            'text_identifier': 'EMAIL_ENROLLMENT_REMINDER',
            'subject': "Recordatori d'inscripció a l'activitat: {activitat_nom}",
            'body': """<table align="center" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f0f0f0">
    <tr>
      <td align="center" valign="top" class="em_text1 pad10">
        <p>Instruccions per participar al taller</p>
      </td>
    </tr>
    <tr>
      <td height="15" style="font-size:0px; line-height:0px; height:15px;">&nbsp;</td>
    </tr>
    <tr>
      <td align="center" valign="top" style="font-family:'Open Sans', Arial, sans-serif; font-size:22px;
      line-height:22px; color:#000; letter-spacing:2px; padding-bottom:12px;" class="pad10">
        <strong>{activitat_nom}</strong> de {ateneu_nom}
      </td>
    </tr>
    <tr>
      <td height="25" class="em_h20" style="font-size:0px; line-height:0px; height:25px;">&nbsp;</td>
    </tr>
    <tr>
      <td align="left" valign="top" style="padding: 0px 40px 10px 40px" bgcolor="#fafafa" class="em_text1 pad10">
        <p style="padding-top: 20px">Hola {persona_nom}!</p>
        <p style="padding-top: 20px">T'enviem aquest correu perquè tens una inscripció a aquesta sessió i s'acosta la data:</p>
        <p style="margin-left: 60px"><strong>Data:</strong> {activitat_data_inici}</p>
        <p style="margin-left: 60px"><strong>Hora:</strong> {activitat_hora_inici}</p>
        <p style="margin-left: 60px"><strong>Lloc:</strong> {activitat_lloc}</p>
        <p style="padding-top: 20px">{activitat_instruccions}</p>
        <p style="padding-top: 20px">Per accedir als fitxers adjunts, enllaç a la videotrucada i gestionar la teva 
            inscripció, ves a <a href="{absolute_url_activity}">la fitxa de la sessió</a>.</p>
        <p style="padding-top: 20px">Es tracta d'una formació gratuïta subvencionada, per això et demanem que 
            si finalment no pots venir ens avisis amb antelació per poder obrir la plaça a una altra persona.<br>
          Per fer-ho pots gestionar les teves inscripcions accedint a l'aplicació amb el teu compte i anant a 
        l'apartat <a href="{absolute_url_my_activities}">Perfil -> Els Meus Cursos</a>.</p>
      </td>
    </tr>
    <tr>
      <td align="center" class="em_text1 pad10" bgcolor="#fafafa" style="padding-bottom: 15px;">
        <a href="{url_web_ateneu}" style="color:#e94e1b; text-decoration:none; font-weight: bold;">Fins aviat!</a>
      </td>
    </tr>
    </table>""",
            'default_template_path': 'emails/front_generic.html'
        },
    )
    print('EMAIL_ENROLLMENT_REMINDER template updated.')


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0067_auto_20200805_1911'),
    ]

    operations = [
        migrations.RunPython(populate_mail_templates),
    ]
