# Generated by Django 2.2.7 on 2020-09-15 11:35

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0070_auto_20200915_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Prioritza les etiquetes que apareixen auto-completades. Si escrius una etiqueta amb un espai creurà que son dues etiquetes, per evitar-ho escriu-la entre cometes dobles, "etiqueta amb espais".', to='coopolis.Tagulous_Project_tags', verbose_name='etiquetes'),
        ),
    ]
