# Generated by Django 2.2.7 on 2021-03-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0076_auto_20210111_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='covid_crisis',
            field=models.BooleanField(default=False, verbose_name='Crisi covid'),
        ),
    ]
