# Generated by Django 2.2.7 on 2021-03-01 14:49

from django.db import migrations


def update_covid_boolean(apps, schema_editor):
    print('')
    projectstage_model = apps.get_model('coopolis', 'ProjectStage')
    obj = projectstage_model.objects.filter(
        stage_type=10
    ).update(covid_crisis=True)

    print("Nou camp Covid omplert amb la dada corresponent.")


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0077_projectstage_covid_crisis'),
    ]

    operations = [
        migrations.RunPython(update_covid_boolean),
    ]
