# Generated by Django 2.2.7 on 2021-03-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0080_auto_20210304_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'subtipus',
                'verbose_name_plural': 'subtipus',
            },
        ),
        migrations.AddField(
            model_name='projectstage',
            name='stage_subtype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.StageSubtype', verbose_name='subtipus'),
        ),
    ]
