# Generated by Django 2.2.7 on 2021-03-05 14:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0080_auto_20210304_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='date_end',
            field=models.DateField(blank=True, help_text="AQUEST CAMP S'ELIMINARÀ PROPERAMENT, l'inici i finalització de l'acompanyament es calcularà a partir de les dates de les Sessions d'Acompanyament.", null=True, verbose_name='[obsolet] data de finalització'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date.today, help_text="AQUEST CAMP S'ELIMINARÀ PROPERAMENT, l'inici i finalització de l'acompanyament es calcularà a partir de les dates de les Sessions d'Acompanyament.", null=True, verbose_name="[obsolet] data d'inici"),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='follow_up',
            field=models.TextField(blank=True, help_text="AQUEST CAMP S'ELIMINARÀ PROPERAMENT, cal que el seguiment el poseu en el nou format, mitjançant 'Sessions d'acompanyament'.", null=True, verbose_name='[obsolet] Seguiment'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='hours',
            field=models.IntegerField(blank=True, help_text="AQUEST CAMP S'ELIMINARÀ PROPERAMENT, cal que les hores les poseu en el nou format, mitjançant 'Sessions d'acompanyament'.", null=True, verbose_name="[obsolet] Número d'hores"),
        ),
        migrations.CreateModel(
            name='ProjectStageSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='data')),
                ('hours', models.IntegerField(blank=True, help_text='Camp necessari per la justificació.', null=True, verbose_name="número d'hores")),
                ('follow_up', models.TextField(blank=True, null=True, verbose_name='seguiment')),
                ('project_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stages', to='coopolis.ProjectStage', verbose_name="justificació d'acompanyament")),
                ('session_responsible', models.ForeignKey(blank=True, help_text="Persona de l'equip que ha facilitat la sessió. Per aparèixer al desplegable, cal que la persona tingui activada la opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_sessions', to=settings.AUTH_USER_MODEL, verbose_name='persona facilitadora')),
            ],
            options={
                'verbose_name': "sessió d'acompanyament",
                'verbose_name_plural': "sessions d'acompanyament",
            },
        ),
    ]
