# Generated by Django 2.2.7 on 2021-03-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0047_auto_20210301_1531'),
        ('coopolis', '0081_auto_20210305_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstagesession',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity', verbose_name='Entitat'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity', verbose_name='[obsolet] Entitat'),
        ),
        migrations.AlterField(
            model_name='projectstagesession',
            name='project_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_sessions', to='coopolis.ProjectStage', verbose_name="justificació d'acompanyament"),
        ),
    ]
