# Generated by Django 2.2.7 on 2021-04-12 14:09

import coopolis.storage_backends
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0047_auto_20210301_1531'),
        ('coopolis', '0082_datamigr_subtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='date_end',
            field=models.DateField(blank=True, help_text="AQUEST CAMP S'ELIMINARÀ PROPERAMENT, l'inici i finalització de l'acompanyament es calcularà a partir de les dates de les Sessions d'Acompanyament.", null=True, verbose_name='[obsolet] data de finalització'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='date_start',
            field=models.DateField(auto_now_add=True,
                                   verbose_name="data d'inici"),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity', verbose_name='[obsolet] Entitat'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='follow_up',
            field=models.TextField(blank=True, help_text="AQUEST CAMP S'ELIMINARÀ PROPERAMENT, cal que el seguiment el poseu en el nou format, mitjançant 'Sessions d'acompanyament'.", null=True, verbose_name='[obsolet] Seguiment'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='hours',
            field=models.IntegerField(blank=True, help_text="AQUEST CAMP S'ELIMINARÀ PROPERAMENT, cal que les hores les poseu en el nou format, mitjançant 'Sessions d'acompanyament'.", null=True, verbose_name="[obsolet] Número d'hores"),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='scanned_certificate',
            field=models.FileField(blank=True, max_length=250, null=True, storage=coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Certificat'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='scanned_signatures',
            field=models.FileField(blank=True, max_length=250, null=True, storage=coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='[obsolet] Fitxa de projectes (document amb signatures)'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage_type',
            field=models.CharField(choices=[('11', 'Creació'), ('12', 'Consolidació'), ('9', 'Incubació'), ('10', '[obsolet] Crisi Covid')], default=1, max_length=2, verbose_name="tipus d'acompanyament"),
        ),
        migrations.CreateModel(
            name='ProjectStageSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='data')),
                ('hours', models.IntegerField(blank=True, help_text='Camp necessari per la justificació.', null=True, verbose_name="número d'hores")),
                ('follow_up', models.TextField(blank=True, null=True, verbose_name='seguiment')),
                ('entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc_courses.Entity', verbose_name='Entitat')),
                ('project_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_sessions', to='coopolis.ProjectStage', verbose_name="justificació d'acompanyament")),
                ('session_responsible', models.ForeignKey(blank=True, help_text="Persona de l'equip que ha facilitat la sessió. Per aparèixer al desplegable, cal que la persona tingui activada la opció 'Membre del personal'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_sessions', to=settings.AUTH_USER_MODEL, verbose_name='persona facilitadora')),
            ],
            options={
                'verbose_name': "Sessió d'acompanyament",
                'verbose_name_plural': "Sessions d'acompanyament",
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=250, storage=coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='fitxer')),
                ('name', models.CharField(help_text="Els fitxers antics tenen com a etiqueta el propi nom de l'arxiu, però aquí hi pot anar qualsevol text descriptiu.", max_length=250, verbose_name='Etiqueta')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='coopolis.Project')),
            ],
            options={
                'verbose_name': 'fitxer',
                'verbose_name_plural': 'fitxers',
                'ordering': ['name'],
            },
        ),
    ]
