# Generated by Django 2.2.7 on 2021-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0083_auto_20210412_1409'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activitypoll',
            name='unique_answer',
        ),
        migrations.RemoveField(
            model_name='activitypoll',
            name='user',
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage_type',
            field=models.CharField(choices=[('11', 'Creació'), ('12', 'Consolidació'), ('9', 'Incubació')], default=1, max_length=2, verbose_name="tipus d'acompanyament"),
        ),
    ]
