# Generated by Django 3.2.14 on 2022-11-17 17:43

import apps.cc_users.managers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_load_town_fixtures'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_User_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correu electrònic')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('fake_email', models.BooleanField(default=False, help_text='Marca aquesta casella si el correu és inventat, i desmarca-la si mai el canvieu pel correu real. Ens ajudarà a mantenir la base de dadesneta.', verbose_name='e-mail inventat')),
                ('username', models.CharField(max_length=150, null=True, verbose_name="nom d'usuari/a")),
                ('surname2', models.CharField(blank=True, max_length=50, null=True, verbose_name='segon cognom')),
                ('id_number', models.CharField(max_length=11, null=True, verbose_name='DNI/NIE/Passaport')),
                ('cannot_share_id', models.BooleanField(default=False, verbose_name="Si degut a la teva situació legal et suposa un inconvenient indicar el DNI, deixa'l en blanc i marca aquesta casella")),
                ('gender', models.CharField(blank=True, choices=[('OTHER', 'Altre'), ('FEMALE', 'Dona'), ('MALE', 'Home')], max_length=10, null=True, verbose_name='gènere')),
                ('birth_place', models.TextField(blank=True, choices=[('BARCELONA', 'Barcelona'), ('CATALUNYA', 'Catalunya'), ('ESPANYA', 'Espanya'), ('OTHER', 'Altre')], null=True, verbose_name='lloc de naixement')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='data de naixement')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='adreça')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='telèfon')),
                ('educational_level', models.TextField(blank=True, choices=[('MASTER', 'Màster / Postgrau'), ('HIGH_SCHOOL', 'Secundària'), ('WITHOUT_STUDIES', 'Sense estudis'), ('FP', 'Formació professional'), ('UNIVERSITY', 'Estudis universitaris'), ('ELEMENTARY_SCHOOL', 'Primària')], null=True, verbose_name="nivell d'estudis")),
                ('employment_situation', models.TextField(blank=True, choices=[('SELF_EMPLOYED', 'En actiu per compte propi'), ('UNEMPLOYMENT_BENEFIT_RECEIVER', 'Perceptora de prestacions socials'), ('UNEMPLOYMENT_BENEFIT_REQUESTED', "Demandant d'ocupació"), ('EMPLOYED_WORKER', 'En actiu per compte aliè')], null=True, verbose_name='situació laboral')),
                ('discovered_us', models.TextField(blank=True, choices=[('INTERNET', 'Per internet i xarxes socials'), ('FRIEND', "A través d'un conegut"), ('PREVIOUS_ACTIVITY', "Per una activitat de l'ateneu"), ('OTHER', 'Altres')], null=True, verbose_name='com ens has conegut')),
                ('project_involved', models.CharField(blank=True, max_length=240, null=True, verbose_name="si participes a un projecte cooperatiu o de l'ESS, indica'ns-el")),
                ('cooperativism_knowledge', models.TextField(blank=True, help_text='Tens coneixements / formació / experiència en cooperativisme? Quina? Cursos realitzats?', null=True, verbose_name='coneixements previs')),
                ('authorize_communications', models.BooleanField(default=False, verbose_name='autoritza comunicació publicitària')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Prioritza les etiquetes que apareixen auto-completades. Si escrius una etiqueta amb un espai creurà que son dues etiquetes, per evitar-ho escriu-la entre cometes dobles, "etiqueta amb espais".', to='cc_users.Tagulous_User_tags', verbose_name='etiquetes')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.town', verbose_name='població actual')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'persones',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.cc_users.managers.CCUserManager()),
            ],
        ),
    ]
