# Generated by Django 3.2.14 on 2022-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_users', '0002_data_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='town',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('OTHER', 'No binari'), ('FEMALE', 'Dona'), ('MALE', 'Home')], max_length=10, null=True, verbose_name='gènere'),
        ),
    ]
